package net.minecraft.init;

import com.google.common.collect.Sets;
import java.util.Set;
import javax.annotation.Nullable;
import net.minecraft.block.Block;
import net.minecraft.block.BlockBeacon;
import net.minecraft.block.BlockBush;
import net.minecraft.block.BlockCactus;
import net.minecraft.block.BlockCauldron;
import net.minecraft.block.BlockChest;
import net.minecraft.block.BlockDaylightDetector;
import net.minecraft.block.BlockDeadBush;
import net.minecraft.block.BlockDoor;
import net.minecraft.block.BlockDoublePlant;
import net.minecraft.block.BlockDynamicLiquid;
import net.minecraft.block.BlockFire;
import net.minecraft.block.BlockFlower;
import net.minecraft.block.BlockGrass;
import net.minecraft.block.BlockHopper;
import net.minecraft.block.BlockLeaves;
import net.minecraft.block.BlockMycelium;
import net.minecraft.block.BlockPistonBase;
import net.minecraft.block.BlockPistonExtension;
import net.minecraft.block.BlockPistonMoving;
import net.minecraft.block.BlockPortal;
import net.minecraft.block.BlockRedstoneComparator;
import net.minecraft.block.BlockRedstoneRepeater;
import net.minecraft.block.BlockRedstoneWire;
import net.minecraft.block.BlockReed;
import net.minecraft.block.BlockSand;
import net.minecraft.block.BlockSkull;
import net.minecraft.block.BlockSlab;
import net.minecraft.block.BlockStainedGlass;
import net.minecraft.block.BlockStainedGlassPane;
import net.minecraft.block.BlockStaticLiquid;
import net.minecraft.block.BlockTallGrass;
import net.minecraft.block.BlockTripWireHook;
import net.minecraft.util.ResourceLocation;

public class Blocks
{
    private static final Set<Block> field_185780_dg;
    public static final Block AIR;
    public static final Block STONE;
    public static final BlockGrass GRASS;
    public static final Block DIRT;
    public static final Block COBBLESTONE;
    public static final Block field_150344_f;
    public static final Block field_150345_g;
    public static final Block BEDROCK;
    public static final BlockDynamicLiquid field_150358_i;
    public static final BlockStaticLiquid WATER;
    public static final BlockDynamicLiquid field_150356_k;
    public static final BlockStaticLiquid LAVA;
    public static final BlockSand SAND;
    public static final Block GRAVEL;
    public static final Block GOLD_ORE;
    public static final Block IRON_ORE;
    public static final Block COAL_ORE;
    public static final Block field_150364_r;
    public static final Block field_150363_s;
    public static final BlockLeaves field_150362_t;
    public static final BlockLeaves field_150361_u;
    public static final Block SPONGE;
    public static final Block GLASS;
    public static final Block LAPIS_ORE;
    public static final Block LAPIS_BLOCK;
    public static final Block DISPENSER;
    public static final Block SANDSTONE;
    public static final Block field_150323_B;
    public static final Block field_150324_C;
    public static final Block field_150318_D;
    public static final Block DETECTOR_RAIL;
    public static final BlockPistonBase STICKY_PISTON;
    public static final Block field_150321_G;
    public static final BlockTallGrass field_150329_H;
    public static final BlockDeadBush field_150330_I;
    public static final BlockPistonBase PISTON;
    public static final BlockPistonExtension PISTON_HEAD;
    public static final Block field_150325_L;
    public static final BlockPistonMoving field_180384_M;
    public static final BlockFlower field_150327_N;
    public static final BlockFlower field_150328_O;
    public static final BlockBush BROWN_MUSHROOM;
    public static final BlockBush RED_MUSHROOM;
    public static final Block GOLD_BLOCK;
    public static final Block IRON_BLOCK;
    public static final BlockSlab field_150334_T;
    public static final BlockSlab STONE_SLAB;
    public static final Block field_150336_V;
    public static final Block TNT;
    public static final Block BOOKSHELF;
    public static final Block MOSSY_COBBLESTONE;
    public static final Block OBSIDIAN;
    public static final Block TORCH;
    public static final BlockFire FIRE;
    public static final Block SPAWNER;
    public static final Block OAK_STAIRS;
    public static final BlockChest CHEST;
    public static final BlockRedstoneWire REDSTONE_WIRE;
    public static final Block DIAMOND_ORE;
    public static final Block DIAMOND_BLOCK;
    public static final Block CRAFTING_TABLE;
    public static final Block WHEAT;
    public static final Block FARMLAND;
    public static final Block FURNACE;
    public static final Block field_150470_am;
    public static final Block field_150472_an;
    public static final BlockDoor OAK_DOOR;
    public static final BlockDoor SPRUCE_DOOR;
    public static final BlockDoor BIRCH_DOOR;
    public static final BlockDoor JUNGLE_DOOR;
    public static final BlockDoor ACACIA_DOOR;
    public static final BlockDoor DARK_OAK_DOOR;
    public static final Block LADDER;
    public static final Block RAIL;
    public static final Block field_150446_ar;
    public static final Block field_150444_as;
    public static final Block LEVER;
    public static final Block STONE_PRESSURE_PLATE;
    public static final BlockDoor IRON_DOOR;
    public static final Block field_150452_aw;
    public static final Block REDSTONE_ORE;
    public static final Block field_150439_ay;
    public static final Block field_150437_az;
    public static final Block REDSTONE_TORCH;
    public static final Block STONE_BUTTON;
    public static final Block field_150431_aC;
    public static final Block ICE;
    public static final Block SNOW;
    public static final BlockCactus CACTUS;
    public static final Block CLAY;
    public static final BlockReed field_150436_aH;
    public static final Block JUKEBOX;
    public static final Block OAK_FENCE;
    public static final Block SPRUCE_FENCE;
    public static final Block BIRCH_FENCE;
    public static final Block JUNGLE_FENCE;
    public static final Block DARK_OAK_FENCE;
    public static final Block ACACIA_FENCE;
    public static final Block PUMPKIN;
    public static final Block NETHERRACK;
    public static final Block SOUL_SAND;
    public static final Block GLOWSTONE;
    public static final BlockPortal NETHER_PORTAL;
    public static final Block field_150428_aP;
    public static final Block CAKE;
    public static final BlockRedstoneRepeater field_150413_aR;
    public static final BlockRedstoneRepeater field_150416_aS;
    public static final Block field_150415_aT;
    public static final Block field_150418_aU;
    public static final Block field_150417_aV;
    public static final Block BROWN_MUSHROOM_BLOCK;
    public static final Block RED_MUSHROOM_BLOCK;
    public static final Block IRON_BARS;
    public static final Block GLASS_PANE;
    public static final Block MELON;
    public static final Block PUMPKIN_STEM;
    public static final Block MELON_STEM;
    public static final Block VINE;
    public static final Block OAK_FENCE_GATE;
    public static final Block SPRUCE_FENCE_GATE;
    public static final Block BIRCH_FENCE_GATE;
    public static final Block JUNGLE_FENCE_GATE;
    public static final Block DARK_OAK_FENCE_GATE;
    public static final Block ACACIA_FENCE_GATE;
    public static final Block BRICK_STAIRS;
    public static final Block STONE_BRICK_STAIRS;
    public static final BlockMycelium MYCELIUM;
    public static final Block field_150392_bi;
    public static final Block field_150385_bj;
    public static final Block NETHER_BRICK_FENCE;
    public static final Block NETHER_BRICK_STAIRS;
    public static final Block NETHER_WART;
    public static final Block ENCHANTING_TABLE;
    public static final Block BREWING_STAND;
    public static final BlockCauldron CAULDRON;
    public static final Block END_PORTAL;
    public static final Block END_PORTAL_FRAME;
    public static final Block END_STONE;
    public static final Block DRAGON_EGG;
    public static final Block REDSTONE_LAMP;
    public static final Block field_150374_bv;
    public static final BlockSlab field_150373_bw;
    public static final BlockSlab field_150376_bx;
    public static final Block COCOA;
    public static final Block SANDSTONE_STAIRS;
    public static final Block EMERALD_ORE;
    public static final Block ENDER_CHEST;
    public static final BlockTripWireHook TRIPWIRE_HOOK;
    public static final Block TRIPWIRE;
    public static final Block EMERALD_BLOCK;
    public static final Block SPRUCE_STAIRS;
    public static final Block BIRCH_STAIRS;
    public static final Block JUNGLE_STAIRS;
    public static final Block COMMAND_BLOCK;
    public static final BlockBeacon BEACON;
    public static final Block COBBLESTONE_WALL;
    public static final Block FLOWER_POT;
    public static final Block CARROTS;
    public static final Block POTATOES;
    public static final Block field_150471_bO;
    public static final BlockSkull field_150465_bP;
    public static final Block ANVIL;
    public static final Block TRAPPED_CHEST;
    public static final Block LIGHT_WEIGHTED_PRESSURE_PLATE;
    public static final Block HEAVY_WEIGHTED_PRESSURE_PLATE;
    public static final BlockRedstoneComparator field_150441_bU;
    public static final BlockRedstoneComparator field_150455_bV;
    public static final BlockDaylightDetector DAYLIGHT_DETECTOR;
    public static final BlockDaylightDetector field_180402_cm;
    public static final Block REDSTONE_BLOCK;
    public static final Block field_150449_bY;
    public static final BlockHopper HOPPER;
    public static final Block QUARTZ_BLOCK;
    public static final Block QUARTZ_STAIRS;
    public static final Block ACTIVATOR_RAIL;
    public static final Block DROPPER;
    public static final Block field_150406_ce;
    public static final Block BARRIER;
    public static final Block IRON_TRAPDOOR;
    public static final Block HAY_BLOCK;
    public static final Block field_150404_cg;
    public static final Block TERRACOTTA;
    public static final Block COAL_BLOCK;
    public static final Block PACKED_ICE;
    public static final Block ACACIA_STAIRS;
    public static final Block DARK_OAK_STAIRS;
    public static final Block SLIME_BLOCK;
    public static final BlockDoublePlant field_150398_cm;
    public static final BlockStainedGlass field_150399_cn;
    public static final BlockStainedGlassPane field_150397_co;
    public static final Block PRISMARINE;
    public static final Block SEA_LANTERN;
    public static final Block field_180393_cK;
    public static final Block field_180394_cL;
    public static final Block RED_SANDSTONE;
    public static final Block RED_SANDSTONE_STAIRS;
    public static final BlockSlab field_180388_cO;
    public static final BlockSlab field_180389_cP;
    public static final Block END_ROD;
    public static final Block CHORUS_PLANT;
    public static final Block CHORUS_FLOWER;
    public static final Block PURPUR_BLOCK;
    public static final Block PURPUR_PILLAR;
    public static final Block PURPUR_STAIRS;
    public static final BlockSlab field_185770_cW;
    public static final BlockSlab PURPUR_SLAB;
    public static final Block field_185772_cY;
    public static final Block BEETROOTS;
    public static final Block GRASS_PATH;
    public static final Block END_GATEWAY;
    public static final Block REPEATING_COMMAND_BLOCK;
    public static final Block CHAIN_COMMAND_BLOCK;
    public static final Block FROSTED_ICE;
    public static final Block field_189877_df;
    public static final Block NETHER_WART_BLOCK;
    public static final Block field_189879_dh;
    public static final Block BONE_BLOCK;
    public static final Block STRUCTURE_VOID;
    public static final Block OBSERVER;
    public static final Block WHITE_SHULKER_BOX;
    public static final Block ORANGE_SHULKER_BOX;
    public static final Block MAGENTA_SHULKER_BOX;
    public static final Block LIGHT_BLUE_SHULKER_BOX;
    public static final Block YELLOW_SHULKER_BOX;
    public static final Block LIME_SHULKER_BOX;
    public static final Block PINK_SHULKER_BOX;
    public static final Block GRAY_SHULKER_BOX;
    public static final Block field_190985_dt;
    public static final Block CYAN_SHULKER_BOX;
    public static final Block PURPLE_SHULKER_BOX;
    public static final Block BLUE_SHULKER_BOX;
    public static final Block BROWN_SHULKER_BOX;
    public static final Block GREEN_SHULKER_BOX;
    public static final Block RED_SHULKER_BOX;
    public static final Block BLACK_SHULKER_BOX;
    public static final Block WHITE_GLAZED_TERRACOTTA;
    public static final Block ORANGE_GLAZED_TERRACOTTA;
    public static final Block MAGENTA_GLAZED_TERRACOTTA;
    public static final Block LIGHT_BLUE_GLAZED_TERRACOTTA;
    public static final Block YELLOW_GLAZED_TERRACOTTA;
    public static final Block LIME_GLAZED_TERRACOTTA;
    public static final Block PINK_GLAZED_TERRACOTTA;
    public static final Block GRAY_GLAZED_TERRACOTTA;
    public static final Block field_192435_dJ;
    public static final Block CYAN_GLAZED_TERRACOTTA;
    public static final Block PURPLE_GLAZED_TERRACOTTA;
    public static final Block BLUE_GLAZED_TERRACOTTA;
    public static final Block BROWN_GLAZED_TERRACOTTA;
    public static final Block GREEN_GLAZED_TERRACOTTA;
    public static final Block RED_GLAZED_TERRACOTTA;
    public static final Block BLACK_GLAZED_TERRACOTTA;
    public static final Block field_192443_dR;
    public static final Block field_192444_dS;
    public static final Block STRUCTURE_BLOCK;

    @Nullable
    private static Block func_180383_a(String p_180383_0_)
    {
        Block block = Block.field_149771_c.getOrDefault(new ResourceLocation(p_180383_0_));

        if (!field_185780_dg.add(block))
        {
            throw new IllegalStateException("Invalid Block requested: " + p_180383_0_);
        }
        else
        {
            return block;
        }
    }

    static
    {
        if (!Bootstrap.func_179869_a())
        {
            throw new RuntimeException("Accessed Blocks before Bootstrap!");
        }
        else
        {
            field_185780_dg = Sets.<Block>newHashSet();
            AIR = func_180383_a("air");
            STONE = func_180383_a("stone");
            GRASS = (BlockGrass)func_180383_a("grass");
            DIRT = func_180383_a("dirt");
            COBBLESTONE = func_180383_a("cobblestone");
            field_150344_f = func_180383_a("planks");
            field_150345_g = func_180383_a("sapling");
            BEDROCK = func_180383_a("bedrock");
            field_150358_i = (BlockDynamicLiquid)func_180383_a("flowing_water");
            WATER = (BlockStaticLiquid)func_180383_a("water");
            field_150356_k = (BlockDynamicLiquid)func_180383_a("flowing_lava");
            LAVA = (BlockStaticLiquid)func_180383_a("lava");
            SAND = (BlockSand)func_180383_a("sand");
            GRAVEL = func_180383_a("gravel");
            GOLD_ORE = func_180383_a("gold_ore");
            IRON_ORE = func_180383_a("iron_ore");
            COAL_ORE = func_180383_a("coal_ore");
            field_150364_r = func_180383_a("log");
            field_150363_s = func_180383_a("log2");
            field_150362_t = (BlockLeaves)func_180383_a("leaves");
            field_150361_u = (BlockLeaves)func_180383_a("leaves2");
            SPONGE = func_180383_a("sponge");
            GLASS = func_180383_a("glass");
            LAPIS_ORE = func_180383_a("lapis_ore");
            LAPIS_BLOCK = func_180383_a("lapis_block");
            DISPENSER = func_180383_a("dispenser");
            SANDSTONE = func_180383_a("sandstone");
            field_150323_B = func_180383_a("noteblock");
            field_150324_C = func_180383_a("bed");
            field_150318_D = func_180383_a("golden_rail");
            DETECTOR_RAIL = func_180383_a("detector_rail");
            STICKY_PISTON = (BlockPistonBase)func_180383_a("sticky_piston");
            field_150321_G = func_180383_a("web");
            field_150329_H = (BlockTallGrass)func_180383_a("tallgrass");
            field_150330_I = (BlockDeadBush)func_180383_a("deadbush");
            PISTON = (BlockPistonBase)func_180383_a("piston");
            PISTON_HEAD = (BlockPistonExtension)func_180383_a("piston_head");
            field_150325_L = func_180383_a("wool");
            field_180384_M = (BlockPistonMoving)func_180383_a("piston_extension");
            field_150327_N = (BlockFlower)func_180383_a("yellow_flower");
            field_150328_O = (BlockFlower)func_180383_a("red_flower");
            BROWN_MUSHROOM = (BlockBush)func_180383_a("brown_mushroom");
            RED_MUSHROOM = (BlockBush)func_180383_a("red_mushroom");
            GOLD_BLOCK = func_180383_a("gold_block");
            IRON_BLOCK = func_180383_a("iron_block");
            field_150334_T = (BlockSlab)func_180383_a("double_stone_slab");
            STONE_SLAB = (BlockSlab)func_180383_a("stone_slab");
            field_150336_V = func_180383_a("brick_block");
            TNT = func_180383_a("tnt");
            BOOKSHELF = func_180383_a("bookshelf");
            MOSSY_COBBLESTONE = func_180383_a("mossy_cobblestone");
            OBSIDIAN = func_180383_a("obsidian");
            TORCH = func_180383_a("torch");
            FIRE = (BlockFire)func_180383_a("fire");
            SPAWNER = func_180383_a("mob_spawner");
            OAK_STAIRS = func_180383_a("oak_stairs");
            CHEST = (BlockChest)func_180383_a("chest");
            REDSTONE_WIRE = (BlockRedstoneWire)func_180383_a("redstone_wire");
            DIAMOND_ORE = func_180383_a("diamond_ore");
            DIAMOND_BLOCK = func_180383_a("diamond_block");
            CRAFTING_TABLE = func_180383_a("crafting_table");
            WHEAT = func_180383_a("wheat");
            FARMLAND = func_180383_a("farmland");
            FURNACE = func_180383_a("furnace");
            field_150470_am = func_180383_a("lit_furnace");
            field_150472_an = func_180383_a("standing_sign");
            OAK_DOOR = (BlockDoor)func_180383_a("wooden_door");
            SPRUCE_DOOR = (BlockDoor)func_180383_a("spruce_door");
            BIRCH_DOOR = (BlockDoor)func_180383_a("birch_door");
            JUNGLE_DOOR = (BlockDoor)func_180383_a("jungle_door");
            ACACIA_DOOR = (BlockDoor)func_180383_a("acacia_door");
            DARK_OAK_DOOR = (BlockDoor)func_180383_a("dark_oak_door");
            LADDER = func_180383_a("ladder");
            RAIL = func_180383_a("rail");
            field_150446_ar = func_180383_a("stone_stairs");
            field_150444_as = func_180383_a("wall_sign");
            LEVER = func_180383_a("lever");
            STONE_PRESSURE_PLATE = func_180383_a("stone_pressure_plate");
            IRON_DOOR = (BlockDoor)func_180383_a("iron_door");
            field_150452_aw = func_180383_a("wooden_pressure_plate");
            REDSTONE_ORE = func_180383_a("redstone_ore");
            field_150439_ay = func_180383_a("lit_redstone_ore");
            field_150437_az = func_180383_a("unlit_redstone_torch");
            REDSTONE_TORCH = func_180383_a("redstone_torch");
            STONE_BUTTON = func_180383_a("stone_button");
            field_150431_aC = func_180383_a("snow_layer");
            ICE = func_180383_a("ice");
            SNOW = func_180383_a("snow");
            CACTUS = (BlockCactus)func_180383_a("cactus");
            CLAY = func_180383_a("clay");
            field_150436_aH = (BlockReed)func_180383_a("reeds");
            JUKEBOX = func_180383_a("jukebox");
            OAK_FENCE = func_180383_a("fence");
            SPRUCE_FENCE = func_180383_a("spruce_fence");
            BIRCH_FENCE = func_180383_a("birch_fence");
            JUNGLE_FENCE = func_180383_a("jungle_fence");
            DARK_OAK_FENCE = func_180383_a("dark_oak_fence");
            ACACIA_FENCE = func_180383_a("acacia_fence");
            PUMPKIN = func_180383_a("pumpkin");
            NETHERRACK = func_180383_a("netherrack");
            SOUL_SAND = func_180383_a("soul_sand");
            GLOWSTONE = func_180383_a("glowstone");
            NETHER_PORTAL = (BlockPortal)func_180383_a("portal");
            field_150428_aP = func_180383_a("lit_pumpkin");
            CAKE = func_180383_a("cake");
            field_150413_aR = (BlockRedstoneRepeater)func_180383_a("unpowered_repeater");
            field_150416_aS = (BlockRedstoneRepeater)func_180383_a("powered_repeater");
            field_150415_aT = func_180383_a("trapdoor");
            field_150418_aU = func_180383_a("monster_egg");
            field_150417_aV = func_180383_a("stonebrick");
            BROWN_MUSHROOM_BLOCK = func_180383_a("brown_mushroom_block");
            RED_MUSHROOM_BLOCK = func_180383_a("red_mushroom_block");
            IRON_BARS = func_180383_a("iron_bars");
            GLASS_PANE = func_180383_a("glass_pane");
            MELON = func_180383_a("melon_block");
            PUMPKIN_STEM = func_180383_a("pumpkin_stem");
            MELON_STEM = func_180383_a("melon_stem");
            VINE = func_180383_a("vine");
            OAK_FENCE_GATE = func_180383_a("fence_gate");
            SPRUCE_FENCE_GATE = func_180383_a("spruce_fence_gate");
            BIRCH_FENCE_GATE = func_180383_a("birch_fence_gate");
            JUNGLE_FENCE_GATE = func_180383_a("jungle_fence_gate");
            DARK_OAK_FENCE_GATE = func_180383_a("dark_oak_fence_gate");
            ACACIA_FENCE_GATE = func_180383_a("acacia_fence_gate");
            BRICK_STAIRS = func_180383_a("brick_stairs");
            STONE_BRICK_STAIRS = func_180383_a("stone_brick_stairs");
            MYCELIUM = (BlockMycelium)func_180383_a("mycelium");
            field_150392_bi = func_180383_a("waterlily");
            field_150385_bj = func_180383_a("nether_brick");
            NETHER_BRICK_FENCE = func_180383_a("nether_brick_fence");
            NETHER_BRICK_STAIRS = func_180383_a("nether_brick_stairs");
            NETHER_WART = func_180383_a("nether_wart");
            ENCHANTING_TABLE = func_180383_a("enchanting_table");
            BREWING_STAND = func_180383_a("brewing_stand");
            CAULDRON = (BlockCauldron)func_180383_a("cauldron");
            END_PORTAL = func_180383_a("end_portal");
            END_PORTAL_FRAME = func_180383_a("end_portal_frame");
            END_STONE = func_180383_a("end_stone");
            DRAGON_EGG = func_180383_a("dragon_egg");
            REDSTONE_LAMP = func_180383_a("redstone_lamp");
            field_150374_bv = func_180383_a("lit_redstone_lamp");
            field_150373_bw = (BlockSlab)func_180383_a("double_wooden_slab");
            field_150376_bx = (BlockSlab)func_180383_a("wooden_slab");
            COCOA = func_180383_a("cocoa");
            SANDSTONE_STAIRS = func_180383_a("sandstone_stairs");
            EMERALD_ORE = func_180383_a("emerald_ore");
            ENDER_CHEST = func_180383_a("ender_chest");
            TRIPWIRE_HOOK = (BlockTripWireHook)func_180383_a("tripwire_hook");
            TRIPWIRE = func_180383_a("tripwire");
            EMERALD_BLOCK = func_180383_a("emerald_block");
            SPRUCE_STAIRS = func_180383_a("spruce_stairs");
            BIRCH_STAIRS = func_180383_a("birch_stairs");
            JUNGLE_STAIRS = func_180383_a("jungle_stairs");
            COMMAND_BLOCK = func_180383_a("command_block");
            BEACON = (BlockBeacon)func_180383_a("beacon");
            COBBLESTONE_WALL = func_180383_a("cobblestone_wall");
            FLOWER_POT = func_180383_a("flower_pot");
            CARROTS = func_180383_a("carrots");
            POTATOES = func_180383_a("potatoes");
            field_150471_bO = func_180383_a("wooden_button");
            field_150465_bP = (BlockSkull)func_180383_a("skull");
            ANVIL = func_180383_a("anvil");
            TRAPPED_CHEST = func_180383_a("trapped_chest");
            LIGHT_WEIGHTED_PRESSURE_PLATE = func_180383_a("light_weighted_pressure_plate");
            HEAVY_WEIGHTED_PRESSURE_PLATE = func_180383_a("heavy_weighted_pressure_plate");
            field_150441_bU = (BlockRedstoneComparator)func_180383_a("unpowered_comparator");
            field_150455_bV = (BlockRedstoneComparator)func_180383_a("powered_comparator");
            DAYLIGHT_DETECTOR = (BlockDaylightDetector)func_180383_a("daylight_detector");
            field_180402_cm = (BlockDaylightDetector)func_180383_a("daylight_detector_inverted");
            REDSTONE_BLOCK = func_180383_a("redstone_block");
            field_150449_bY = func_180383_a("quartz_ore");
            HOPPER = (BlockHopper)func_180383_a("hopper");
            QUARTZ_BLOCK = func_180383_a("quartz_block");
            QUARTZ_STAIRS = func_180383_a("quartz_stairs");
            ACTIVATOR_RAIL = func_180383_a("activator_rail");
            DROPPER = func_180383_a("dropper");
            field_150406_ce = func_180383_a("stained_hardened_clay");
            BARRIER = func_180383_a("barrier");
            IRON_TRAPDOOR = func_180383_a("iron_trapdoor");
            HAY_BLOCK = func_180383_a("hay_block");
            field_150404_cg = func_180383_a("carpet");
            TERRACOTTA = func_180383_a("hardened_clay");
            COAL_BLOCK = func_180383_a("coal_block");
            PACKED_ICE = func_180383_a("packed_ice");
            ACACIA_STAIRS = func_180383_a("acacia_stairs");
            DARK_OAK_STAIRS = func_180383_a("dark_oak_stairs");
            SLIME_BLOCK = func_180383_a("slime");
            field_150398_cm = (BlockDoublePlant)func_180383_a("double_plant");
            field_150399_cn = (BlockStainedGlass)func_180383_a("stained_glass");
            field_150397_co = (BlockStainedGlassPane)func_180383_a("stained_glass_pane");
            PRISMARINE = func_180383_a("prismarine");
            SEA_LANTERN = func_180383_a("sea_lantern");
            field_180393_cK = func_180383_a("standing_banner");
            field_180394_cL = func_180383_a("wall_banner");
            RED_SANDSTONE = func_180383_a("red_sandstone");
            RED_SANDSTONE_STAIRS = func_180383_a("red_sandstone_stairs");
            field_180388_cO = (BlockSlab)func_180383_a("double_stone_slab2");
            field_180389_cP = (BlockSlab)func_180383_a("stone_slab2");
            END_ROD = func_180383_a("end_rod");
            CHORUS_PLANT = func_180383_a("chorus_plant");
            CHORUS_FLOWER = func_180383_a("chorus_flower");
            PURPUR_BLOCK = func_180383_a("purpur_block");
            PURPUR_PILLAR = func_180383_a("purpur_pillar");
            PURPUR_STAIRS = func_180383_a("purpur_stairs");
            field_185770_cW = (BlockSlab)func_180383_a("purpur_double_slab");
            PURPUR_SLAB = (BlockSlab)func_180383_a("purpur_slab");
            field_185772_cY = func_180383_a("end_bricks");
            BEETROOTS = func_180383_a("beetroots");
            GRASS_PATH = func_180383_a("grass_path");
            END_GATEWAY = func_180383_a("end_gateway");
            REPEATING_COMMAND_BLOCK = func_180383_a("repeating_command_block");
            CHAIN_COMMAND_BLOCK = func_180383_a("chain_command_block");
            FROSTED_ICE = func_180383_a("frosted_ice");
            field_189877_df = func_180383_a("magma");
            NETHER_WART_BLOCK = func_180383_a("nether_wart_block");
            field_189879_dh = func_180383_a("red_nether_brick");
            BONE_BLOCK = func_180383_a("bone_block");
            STRUCTURE_VOID = func_180383_a("structure_void");
            OBSERVER = func_180383_a("observer");
            WHITE_SHULKER_BOX = func_180383_a("white_shulker_box");
            ORANGE_SHULKER_BOX = func_180383_a("orange_shulker_box");
            MAGENTA_SHULKER_BOX = func_180383_a("magenta_shulker_box");
            LIGHT_BLUE_SHULKER_BOX = func_180383_a("light_blue_shulker_box");
            YELLOW_SHULKER_BOX = func_180383_a("yellow_shulker_box");
            LIME_SHULKER_BOX = func_180383_a("lime_shulker_box");
            PINK_SHULKER_BOX = func_180383_a("pink_shulker_box");
            GRAY_SHULKER_BOX = func_180383_a("gray_shulker_box");
            field_190985_dt = func_180383_a("silver_shulker_box");
            CYAN_SHULKER_BOX = func_180383_a("cyan_shulker_box");
            PURPLE_SHULKER_BOX = func_180383_a("purple_shulker_box");
            BLUE_SHULKER_BOX = func_180383_a("blue_shulker_box");
            BROWN_SHULKER_BOX = func_180383_a("brown_shulker_box");
            GREEN_SHULKER_BOX = func_180383_a("green_shulker_box");
            RED_SHULKER_BOX = func_180383_a("red_shulker_box");
            BLACK_SHULKER_BOX = func_180383_a("black_shulker_box");
            WHITE_GLAZED_TERRACOTTA = func_180383_a("white_glazed_terracotta");
            ORANGE_GLAZED_TERRACOTTA = func_180383_a("orange_glazed_terracotta");
            MAGENTA_GLAZED_TERRACOTTA = func_180383_a("magenta_glazed_terracotta");
            LIGHT_BLUE_GLAZED_TERRACOTTA = func_180383_a("light_blue_glazed_terracotta");
            YELLOW_GLAZED_TERRACOTTA = func_180383_a("yellow_glazed_terracotta");
            LIME_GLAZED_TERRACOTTA = func_180383_a("lime_glazed_terracotta");
            PINK_GLAZED_TERRACOTTA = func_180383_a("pink_glazed_terracotta");
            GRAY_GLAZED_TERRACOTTA = func_180383_a("gray_glazed_terracotta");
            field_192435_dJ = func_180383_a("silver_glazed_terracotta");
            CYAN_GLAZED_TERRACOTTA = func_180383_a("cyan_glazed_terracotta");
            PURPLE_GLAZED_TERRACOTTA = func_180383_a("purple_glazed_terracotta");
            BLUE_GLAZED_TERRACOTTA = func_180383_a("blue_glazed_terracotta");
            BROWN_GLAZED_TERRACOTTA = func_180383_a("brown_glazed_terracotta");
            GREEN_GLAZED_TERRACOTTA = func_180383_a("green_glazed_terracotta");
            RED_GLAZED_TERRACOTTA = func_180383_a("red_glazed_terracotta");
            BLACK_GLAZED_TERRACOTTA = func_180383_a("black_glazed_terracotta");
            field_192443_dR = func_180383_a("concrete");
            field_192444_dS = func_180383_a("concrete_powder");
            STRUCTURE_BLOCK = func_180383_a("structure_block");
            field_185780_dg.clear();
        }
    }
}
