package net.minecraft.init;

import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemArmorStand;
import net.minecraft.item.ItemBow;
import net.minecraft.item.ItemEmptyMap;
import net.minecraft.item.ItemFishingRod;
import net.minecraft.item.ItemMap;
import net.minecraft.item.ItemPotion;
import net.minecraft.item.ItemShears;
import net.minecraft.util.ResourceLocation;

public class Items
{
    public static final Item AIR;
    public static final Item IRON_SHOVEL;
    public static final Item IRON_PICKAXE;
    public static final Item IRON_AXE;
    public static final Item FLINT_AND_STEEL;
    public static final Item APPLE;
    public static final ItemBow BOW;
    public static final Item ARROW;
    public static final Item SPECTRAL_ARROW;
    public static final Item TIPPED_ARROW;
    public static final Item COAL;
    public static final Item DIAMOND;
    public static final Item IRON_INGOT;
    public static final Item GOLD_INGOT;
    public static final Item IRON_SWORD;
    public static final Item WOODEN_SWORD;
    public static final Item WOODEN_SHOVEL;
    public static final Item WOODEN_PICKAXE;
    public static final Item WOODEN_AXE;
    public static final Item STONE_SWORD;
    public static final Item STONE_SHOVEL;
    public static final Item STONE_PICKAXE;
    public static final Item STONE_AXE;
    public static final Item DIAMOND_SWORD;
    public static final Item DIAMOND_SHOVEL;
    public static final Item DIAMOND_PICKAXE;
    public static final Item DIAMOND_AXE;
    public static final Item STICK;
    public static final Item BOWL;
    public static final Item MUSHROOM_STEW;
    public static final Item GOLDEN_SWORD;
    public static final Item GOLDEN_SHOVEL;
    public static final Item GOLDEN_PICKAXE;
    public static final Item GOLDEN_AXE;
    public static final Item STRING;
    public static final Item FEATHER;
    public static final Item GUNPOWDER;
    public static final Item WOODEN_HOE;
    public static final Item STONE_HOE;
    public static final Item IRON_HOE;
    public static final Item DIAMOND_HOE;
    public static final Item GOLDEN_HOE;
    public static final Item WHEAT_SEEDS;
    public static final Item WHEAT;
    public static final Item BREAD;
    public static final ItemArmor LEATHER_HELMET;
    public static final ItemArmor LEATHER_CHESTPLATE;
    public static final ItemArmor LEATHER_LEGGINGS;
    public static final ItemArmor LEATHER_BOOTS;
    public static final ItemArmor CHAINMAIL_HELMET;
    public static final ItemArmor CHAINMAIL_CHESTPLATE;
    public static final ItemArmor CHAINMAIL_LEGGINGS;
    public static final ItemArmor CHAINMAIL_BOOTS;
    public static final ItemArmor IRON_HELMET;
    public static final ItemArmor IRON_CHESTPLATE;
    public static final ItemArmor IRON_LEGGINGS;
    public static final ItemArmor IRON_BOOTS;
    public static final ItemArmor DIAMOND_HELMET;
    public static final ItemArmor DIAMOND_CHESTPLATE;
    public static final ItemArmor DIAMOND_LEGGINGS;
    public static final ItemArmor DIAMOND_BOOTS;
    public static final ItemArmor GOLDEN_HELMET;
    public static final ItemArmor GOLDEN_CHESTPLATE;
    public static final ItemArmor GOLDEN_LEGGINGS;
    public static final ItemArmor GOLDEN_BOOTS;
    public static final Item FLINT;
    public static final Item PORKCHOP;
    public static final Item COOKED_PORKCHOP;
    public static final Item PAINTING;
    public static final Item GOLDEN_APPLE;
    public static final Item field_151155_ap;
    public static final Item field_179570_aq;
    public static final Item field_179569_ar;
    public static final Item field_179568_as;
    public static final Item field_179567_at;
    public static final Item field_179572_au;
    public static final Item field_179571_av;
    public static final Item BUCKET;
    public static final Item WATER_BUCKET;
    public static final Item LAVA_BUCKET;
    public static final Item MINECART;
    public static final Item SADDLE;
    public static final Item field_151139_aw;
    public static final Item REDSTONE;
    public static final Item SNOWBALL;
    public static final Item OAK_BOAT;
    public static final Item SPRUCE_BOAT;
    public static final Item BIRCH_BOAT;
    public static final Item JUNGLE_BOAT;
    public static final Item ACACIA_BOAT;
    public static final Item DARK_OAK_BOAT;
    public static final Item LEATHER;
    public static final Item MILK_BUCKET;
    public static final Item BRICK;
    public static final Item CLAY_BALL;
    public static final Item field_151120_aE;
    public static final Item PAPER;
    public static final Item BOOK;
    public static final Item SLIME_BALL;
    public static final Item CHEST_MINECART;
    public static final Item FURNACE_MINECART;
    public static final Item EGG;
    public static final Item COMPASS;
    public static final ItemFishingRod FISHING_ROD;
    public static final Item CLOCK;
    public static final Item GLOWSTONE_DUST;
    public static final Item field_151115_aP;
    public static final Item field_179566_aV;
    public static final Item field_151100_aR;
    public static final Item BONE;
    public static final Item SUGAR;
    public static final Item field_151105_aU;
    public static final Item field_151104_aV;
    public static final Item field_151107_aW;
    public static final Item COOKIE;
    public static final ItemMap FILLED_MAP;
    public static final ItemShears SHEARS;
    public static final Item MELON_SLICE;
    public static final Item PUMPKIN_SEEDS;
    public static final Item MELON_SEEDS;
    public static final Item BEEF;
    public static final Item COOKED_BEEF;
    public static final Item CHICKEN;
    public static final Item COOKED_CHICKEN;
    public static final Item MUTTON;
    public static final Item COOKED_MUTTON;
    public static final Item RABBIT;
    public static final Item COOKED_RABBIT;
    public static final Item RABBIT_STEW;
    public static final Item RABBIT_FOOT;
    public static final Item RABBIT_HIDE;
    public static final Item ROTTEN_FLESH;
    public static final Item ENDER_PEARL;
    public static final Item BLAZE_ROD;
    public static final Item GHAST_TEAR;
    public static final Item GOLD_NUGGET;
    public static final Item NETHER_WART;
    public static final ItemPotion POTION;
    public static final ItemPotion SPLASH_POTION;
    public static final ItemPotion LINGERING_POTION;
    public static final Item GLASS_BOTTLE;
    public static final Item DRAGON_BREATH;
    public static final Item SPIDER_EYE;
    public static final Item FERMENTED_SPIDER_EYE;
    public static final Item BLAZE_POWDER;
    public static final Item MAGMA_CREAM;
    public static final Item field_151067_bt;
    public static final Item field_151066_bu;
    public static final Item ENDER_EYE;
    public static final Item GLISTERING_MELON_SLICE;
    public static final Item field_151063_bx;
    public static final Item EXPERIENCE_BOTTLE;
    public static final Item FIRE_CHARGE;
    public static final Item WRITABLE_BOOK;
    public static final Item WRITTEN_BOOK;
    public static final Item EMERALD;
    public static final Item ITEM_FRAME;
    public static final Item field_151162_bE;
    public static final Item CARROT;
    public static final Item POTATO;
    public static final Item BAKED_POTATO;
    public static final Item POISONOUS_POTATO;
    public static final ItemEmptyMap MAP;
    public static final Item GOLDEN_CARROT;
    public static final Item field_151144_bL;
    public static final Item CARROT_ON_A_STICK;
    public static final Item NETHER_STAR;
    public static final Item PUMPKIN_PIE;
    public static final Item field_151152_bP;
    public static final Item field_151154_bQ;
    public static final Item ENCHANTED_BOOK;
    public static final Item field_151132_bS;
    public static final Item field_151130_bT;
    public static final Item QUARTZ;
    public static final Item TNT_MINECART;
    public static final Item HOPPER_MINECART;
    public static final ItemArmorStand ARMOR_STAND;
    public static final Item IRON_HORSE_ARMOR;
    public static final Item GOLDEN_HORSE_ARMOR;
    public static final Item DIAMOND_HORSE_ARMOR;
    public static final Item LEAD;
    public static final Item NAME_TAG;
    public static final Item COMMAND_BLOCK_MINECART;
    public static final Item field_151096_cd;
    public static final Item field_151093_ce;
    public static final Item field_151094_cf;
    public static final Item field_151091_cg;
    public static final Item field_151092_ch;
    public static final Item field_151089_ci;
    public static final Item field_151090_cj;
    public static final Item field_151087_ck;
    public static final Item field_151088_cl;
    public static final Item field_151085_cm;
    public static final Item field_151086_cn;
    public static final Item field_151084_co;
    public static final Item PRISMARINE_SHARD;
    public static final Item PRISMARINE_CRYSTALS;
    public static final Item field_179564_cE;
    public static final Item END_CRYSTAL;
    public static final Item SHIELD;
    public static final Item ELYTRA;
    public static final Item CHORUS_FRUIT;
    public static final Item POPPED_CHORUS_FRUIT;
    public static final Item BEETROOT_SEEDS;
    public static final Item BEETROOT;
    public static final Item BEETROOT_SOUP;
    public static final Item TOTEM_OF_UNDYING;
    public static final Item SHULKER_SHELL;
    public static final Item IRON_NUGGET;
    public static final Item KNOWLEDGE_BOOK;

    private static Item func_179554_a(String p_179554_0_)
    {
        Item item = Item.field_150901_e.getOrDefault(new ResourceLocation(p_179554_0_));

        if (item == null)
        {
            throw new IllegalStateException("Invalid Item requested: " + p_179554_0_);
        }
        else
        {
            return item;
        }
    }

    static
    {
        if (!Bootstrap.func_179869_a())
        {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        }
        else
        {
            AIR = func_179554_a("air");
            IRON_SHOVEL = func_179554_a("iron_shovel");
            IRON_PICKAXE = func_179554_a("iron_pickaxe");
            IRON_AXE = func_179554_a("iron_axe");
            FLINT_AND_STEEL = func_179554_a("flint_and_steel");
            APPLE = func_179554_a("apple");
            BOW = (ItemBow)func_179554_a("bow");
            ARROW = func_179554_a("arrow");
            SPECTRAL_ARROW = func_179554_a("spectral_arrow");
            TIPPED_ARROW = func_179554_a("tipped_arrow");
            COAL = func_179554_a("coal");
            DIAMOND = func_179554_a("diamond");
            IRON_INGOT = func_179554_a("iron_ingot");
            GOLD_INGOT = func_179554_a("gold_ingot");
            IRON_SWORD = func_179554_a("iron_sword");
            WOODEN_SWORD = func_179554_a("wooden_sword");
            WOODEN_SHOVEL = func_179554_a("wooden_shovel");
            WOODEN_PICKAXE = func_179554_a("wooden_pickaxe");
            WOODEN_AXE = func_179554_a("wooden_axe");
            STONE_SWORD = func_179554_a("stone_sword");
            STONE_SHOVEL = func_179554_a("stone_shovel");
            STONE_PICKAXE = func_179554_a("stone_pickaxe");
            STONE_AXE = func_179554_a("stone_axe");
            DIAMOND_SWORD = func_179554_a("diamond_sword");
            DIAMOND_SHOVEL = func_179554_a("diamond_shovel");
            DIAMOND_PICKAXE = func_179554_a("diamond_pickaxe");
            DIAMOND_AXE = func_179554_a("diamond_axe");
            STICK = func_179554_a("stick");
            BOWL = func_179554_a("bowl");
            MUSHROOM_STEW = func_179554_a("mushroom_stew");
            GOLDEN_SWORD = func_179554_a("golden_sword");
            GOLDEN_SHOVEL = func_179554_a("golden_shovel");
            GOLDEN_PICKAXE = func_179554_a("golden_pickaxe");
            GOLDEN_AXE = func_179554_a("golden_axe");
            STRING = func_179554_a("string");
            FEATHER = func_179554_a("feather");
            GUNPOWDER = func_179554_a("gunpowder");
            WOODEN_HOE = func_179554_a("wooden_hoe");
            STONE_HOE = func_179554_a("stone_hoe");
            IRON_HOE = func_179554_a("iron_hoe");
            DIAMOND_HOE = func_179554_a("diamond_hoe");
            GOLDEN_HOE = func_179554_a("golden_hoe");
            WHEAT_SEEDS = func_179554_a("wheat_seeds");
            WHEAT = func_179554_a("wheat");
            BREAD = func_179554_a("bread");
            LEATHER_HELMET = (ItemArmor)func_179554_a("leather_helmet");
            LEATHER_CHESTPLATE = (ItemArmor)func_179554_a("leather_chestplate");
            LEATHER_LEGGINGS = (ItemArmor)func_179554_a("leather_leggings");
            LEATHER_BOOTS = (ItemArmor)func_179554_a("leather_boots");
            CHAINMAIL_HELMET = (ItemArmor)func_179554_a("chainmail_helmet");
            CHAINMAIL_CHESTPLATE = (ItemArmor)func_179554_a("chainmail_chestplate");
            CHAINMAIL_LEGGINGS = (ItemArmor)func_179554_a("chainmail_leggings");
            CHAINMAIL_BOOTS = (ItemArmor)func_179554_a("chainmail_boots");
            IRON_HELMET = (ItemArmor)func_179554_a("iron_helmet");
            IRON_CHESTPLATE = (ItemArmor)func_179554_a("iron_chestplate");
            IRON_LEGGINGS = (ItemArmor)func_179554_a("iron_leggings");
            IRON_BOOTS = (ItemArmor)func_179554_a("iron_boots");
            DIAMOND_HELMET = (ItemArmor)func_179554_a("diamond_helmet");
            DIAMOND_CHESTPLATE = (ItemArmor)func_179554_a("diamond_chestplate");
            DIAMOND_LEGGINGS = (ItemArmor)func_179554_a("diamond_leggings");
            DIAMOND_BOOTS = (ItemArmor)func_179554_a("diamond_boots");
            GOLDEN_HELMET = (ItemArmor)func_179554_a("golden_helmet");
            GOLDEN_CHESTPLATE = (ItemArmor)func_179554_a("golden_chestplate");
            GOLDEN_LEGGINGS = (ItemArmor)func_179554_a("golden_leggings");
            GOLDEN_BOOTS = (ItemArmor)func_179554_a("golden_boots");
            FLINT = func_179554_a("flint");
            PORKCHOP = func_179554_a("porkchop");
            COOKED_PORKCHOP = func_179554_a("cooked_porkchop");
            PAINTING = func_179554_a("painting");
            GOLDEN_APPLE = func_179554_a("golden_apple");
            field_151155_ap = func_179554_a("sign");
            field_179570_aq = func_179554_a("wooden_door");
            field_179569_ar = func_179554_a("spruce_door");
            field_179568_as = func_179554_a("birch_door");
            field_179567_at = func_179554_a("jungle_door");
            field_179572_au = func_179554_a("acacia_door");
            field_179571_av = func_179554_a("dark_oak_door");
            BUCKET = func_179554_a("bucket");
            WATER_BUCKET = func_179554_a("water_bucket");
            LAVA_BUCKET = func_179554_a("lava_bucket");
            MINECART = func_179554_a("minecart");
            SADDLE = func_179554_a("saddle");
            field_151139_aw = func_179554_a("iron_door");
            REDSTONE = func_179554_a("redstone");
            SNOWBALL = func_179554_a("snowball");
            OAK_BOAT = func_179554_a("boat");
            SPRUCE_BOAT = func_179554_a("spruce_boat");
            BIRCH_BOAT = func_179554_a("birch_boat");
            JUNGLE_BOAT = func_179554_a("jungle_boat");
            ACACIA_BOAT = func_179554_a("acacia_boat");
            DARK_OAK_BOAT = func_179554_a("dark_oak_boat");
            LEATHER = func_179554_a("leather");
            MILK_BUCKET = func_179554_a("milk_bucket");
            BRICK = func_179554_a("brick");
            CLAY_BALL = func_179554_a("clay_ball");
            field_151120_aE = func_179554_a("reeds");
            PAPER = func_179554_a("paper");
            BOOK = func_179554_a("book");
            SLIME_BALL = func_179554_a("slime_ball");
            CHEST_MINECART = func_179554_a("chest_minecart");
            FURNACE_MINECART = func_179554_a("furnace_minecart");
            EGG = func_179554_a("egg");
            COMPASS = func_179554_a("compass");
            FISHING_ROD = (ItemFishingRod)func_179554_a("fishing_rod");
            CLOCK = func_179554_a("clock");
            GLOWSTONE_DUST = func_179554_a("glowstone_dust");
            field_151115_aP = func_179554_a("fish");
            field_179566_aV = func_179554_a("cooked_fish");
            field_151100_aR = func_179554_a("dye");
            BONE = func_179554_a("bone");
            SUGAR = func_179554_a("sugar");
            field_151105_aU = func_179554_a("cake");
            field_151104_aV = func_179554_a("bed");
            field_151107_aW = func_179554_a("repeater");
            COOKIE = func_179554_a("cookie");
            FILLED_MAP = (ItemMap)func_179554_a("filled_map");
            SHEARS = (ItemShears)func_179554_a("shears");
            MELON_SLICE = func_179554_a("melon");
            PUMPKIN_SEEDS = func_179554_a("pumpkin_seeds");
            MELON_SEEDS = func_179554_a("melon_seeds");
            BEEF = func_179554_a("beef");
            COOKED_BEEF = func_179554_a("cooked_beef");
            CHICKEN = func_179554_a("chicken");
            COOKED_CHICKEN = func_179554_a("cooked_chicken");
            MUTTON = func_179554_a("mutton");
            COOKED_MUTTON = func_179554_a("cooked_mutton");
            RABBIT = func_179554_a("rabbit");
            COOKED_RABBIT = func_179554_a("cooked_rabbit");
            RABBIT_STEW = func_179554_a("rabbit_stew");
            RABBIT_FOOT = func_179554_a("rabbit_foot");
            RABBIT_HIDE = func_179554_a("rabbit_hide");
            ROTTEN_FLESH = func_179554_a("rotten_flesh");
            ENDER_PEARL = func_179554_a("ender_pearl");
            BLAZE_ROD = func_179554_a("blaze_rod");
            GHAST_TEAR = func_179554_a("ghast_tear");
            GOLD_NUGGET = func_179554_a("gold_nugget");
            NETHER_WART = func_179554_a("nether_wart");
            POTION = (ItemPotion)func_179554_a("potion");
            SPLASH_POTION = (ItemPotion)func_179554_a("splash_potion");
            LINGERING_POTION = (ItemPotion)func_179554_a("lingering_potion");
            GLASS_BOTTLE = func_179554_a("glass_bottle");
            DRAGON_BREATH = func_179554_a("dragon_breath");
            SPIDER_EYE = func_179554_a("spider_eye");
            FERMENTED_SPIDER_EYE = func_179554_a("fermented_spider_eye");
            BLAZE_POWDER = func_179554_a("blaze_powder");
            MAGMA_CREAM = func_179554_a("magma_cream");
            field_151067_bt = func_179554_a("brewing_stand");
            field_151066_bu = func_179554_a("cauldron");
            ENDER_EYE = func_179554_a("ender_eye");
            GLISTERING_MELON_SLICE = func_179554_a("speckled_melon");
            field_151063_bx = func_179554_a("spawn_egg");
            EXPERIENCE_BOTTLE = func_179554_a("experience_bottle");
            FIRE_CHARGE = func_179554_a("fire_charge");
            WRITABLE_BOOK = func_179554_a("writable_book");
            WRITTEN_BOOK = func_179554_a("written_book");
            EMERALD = func_179554_a("emerald");
            ITEM_FRAME = func_179554_a("item_frame");
            field_151162_bE = func_179554_a("flower_pot");
            CARROT = func_179554_a("carrot");
            POTATO = func_179554_a("potato");
            BAKED_POTATO = func_179554_a("baked_potato");
            POISONOUS_POTATO = func_179554_a("poisonous_potato");
            MAP = (ItemEmptyMap)func_179554_a("map");
            GOLDEN_CARROT = func_179554_a("golden_carrot");
            field_151144_bL = func_179554_a("skull");
            CARROT_ON_A_STICK = func_179554_a("carrot_on_a_stick");
            NETHER_STAR = func_179554_a("nether_star");
            PUMPKIN_PIE = func_179554_a("pumpkin_pie");
            field_151152_bP = func_179554_a("fireworks");
            field_151154_bQ = func_179554_a("firework_charge");
            ENCHANTED_BOOK = func_179554_a("enchanted_book");
            field_151132_bS = func_179554_a("comparator");
            field_151130_bT = func_179554_a("netherbrick");
            QUARTZ = func_179554_a("quartz");
            TNT_MINECART = func_179554_a("tnt_minecart");
            HOPPER_MINECART = func_179554_a("hopper_minecart");
            ARMOR_STAND = (ItemArmorStand)func_179554_a("armor_stand");
            IRON_HORSE_ARMOR = func_179554_a("iron_horse_armor");
            GOLDEN_HORSE_ARMOR = func_179554_a("golden_horse_armor");
            DIAMOND_HORSE_ARMOR = func_179554_a("diamond_horse_armor");
            LEAD = func_179554_a("lead");
            NAME_TAG = func_179554_a("name_tag");
            COMMAND_BLOCK_MINECART = func_179554_a("command_block_minecart");
            field_151096_cd = func_179554_a("record_13");
            field_151093_ce = func_179554_a("record_cat");
            field_151094_cf = func_179554_a("record_blocks");
            field_151091_cg = func_179554_a("record_chirp");
            field_151092_ch = func_179554_a("record_far");
            field_151089_ci = func_179554_a("record_mall");
            field_151090_cj = func_179554_a("record_mellohi");
            field_151087_ck = func_179554_a("record_stal");
            field_151088_cl = func_179554_a("record_strad");
            field_151085_cm = func_179554_a("record_ward");
            field_151086_cn = func_179554_a("record_11");
            field_151084_co = func_179554_a("record_wait");
            PRISMARINE_SHARD = func_179554_a("prismarine_shard");
            PRISMARINE_CRYSTALS = func_179554_a("prismarine_crystals");
            field_179564_cE = func_179554_a("banner");
            END_CRYSTAL = func_179554_a("end_crystal");
            SHIELD = func_179554_a("shield");
            ELYTRA = func_179554_a("elytra");
            CHORUS_FRUIT = func_179554_a("chorus_fruit");
            POPPED_CHORUS_FRUIT = func_179554_a("chorus_fruit_popped");
            BEETROOT_SEEDS = func_179554_a("beetroot_seeds");
            BEETROOT = func_179554_a("beetroot");
            BEETROOT_SOUP = func_179554_a("beetroot_soup");
            TOTEM_OF_UNDYING = func_179554_a("totem_of_undying");
            SHULKER_SHELL = func_179554_a("shulker_shell");
            IRON_NUGGET = func_179554_a("iron_nugget");
            KNOWLEDGE_BOOK = func_179554_a("knowledge_book");
        }
    }
}
