package net.minecraft.init;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;

public class SoundEvents
{
    public static final SoundEvent AMBIENT_CAVE;
    public static final SoundEvent BLOCK_ANVIL_BREAK;
    public static final SoundEvent BLOCK_ANVIL_DESTROY;
    public static final SoundEvent BLOCK_ANVIL_FALL;
    public static final SoundEvent BLOCK_ANVIL_HIT;
    public static final SoundEvent BLOCK_ANVIL_LAND;
    public static final SoundEvent BLOCK_ANVIL_PLACE;
    public static final SoundEvent BLOCK_ANVIL_STEP;
    public static final SoundEvent BLOCK_ANVIL_USE;
    public static final SoundEvent ENTITY_ARMOR_STAND_BREAK;
    public static final SoundEvent ENTITY_ARMOR_STAND_FALL;
    public static final SoundEvent ENTITY_ARMOR_STAND_HIT;
    public static final SoundEvent ENTITY_ARMOR_STAND_PLACE;
    public static final SoundEvent ITEM_ARMOR_EQUIP_CHAIN;
    public static final SoundEvent ITEM_ARMOR_EQUIP_DIAMOND;
    public static final SoundEvent ITEM_ARMOR_EQUIP_ELYTRA;
    public static final SoundEvent ITEM_ARMOR_EQUIP_GENERIC;
    public static final SoundEvent ITEM_ARMOR_EQUIP_GOLD;
    public static final SoundEvent ITEM_ARMOR_EQUIP_IRON;
    public static final SoundEvent ITEM_ARMOR_EQUIP_LEATHER;
    public static final SoundEvent ENTITY_ARROW_HIT;
    public static final SoundEvent ENTITY_ARROW_HIT_PLAYER;
    public static final SoundEvent ENTITY_ARROW_SHOOT;
    public static final SoundEvent ENTITY_BAT_AMBIENT;
    public static final SoundEvent ENTITY_BAT_DEATH;
    public static final SoundEvent ENTITY_BAT_HURT;
    public static final SoundEvent ENTITY_BAT_LOOP;
    public static final SoundEvent ENTITY_BAT_TAKEOFF;
    public static final SoundEvent ENTITY_BLAZE_AMBIENT;
    public static final SoundEvent ENTITY_BLAZE_BURN;
    public static final SoundEvent ENTITY_BLAZE_DEATH;
    public static final SoundEvent ENTITY_BLAZE_HURT;
    public static final SoundEvent ENTITY_BLAZE_SHOOT;
    public static final SoundEvent ENTITY_BOAT_PADDLE_LAND;
    public static final SoundEvent ENTITY_BOAT_PADDLE_WATER;
    public static final SoundEvent ENTITY_FISHING_BOBBER_RETRIEVE;
    public static final SoundEvent ENTITY_FISHING_BOBBER_SPLASH;
    public static final SoundEvent ENTITY_FISHING_BOBBER_THROW;
    public static final SoundEvent ITEM_BOTTLE_EMPTY;
    public static final SoundEvent ITEM_BOTTLE_FILL;
    public static final SoundEvent ITEM_BOTTLE_FILL_DRAGONBREATH;
    public static final SoundEvent BLOCK_BREWING_STAND_BREW;
    public static final SoundEvent ITEM_BUCKET_EMPTY;
    public static final SoundEvent ITEM_BUCKET_EMPTY_LAVA;
    public static final SoundEvent ITEM_BUCKET_FILL;
    public static final SoundEvent ITEM_BUCKET_FILL_LAVA;
    public static final SoundEvent ENTITY_CAT_AMBIENT;
    public static final SoundEvent ENTITY_CAT_DEATH;
    public static final SoundEvent ENTITY_CAT_HISS;
    public static final SoundEvent ENTITY_CAT_HURT;
    public static final SoundEvent ENTITY_CAT_PURR;
    public static final SoundEvent ENTITY_CAT_PURREOW;
    public static final SoundEvent BLOCK_CHEST_CLOSE;
    public static final SoundEvent BLOCK_CHEST_LOCKED;
    public static final SoundEvent BLOCK_CHEST_OPEN;
    public static final SoundEvent ENTITY_CHICKEN_AMBIENT;
    public static final SoundEvent ENTITY_CHICKEN_DEATH;
    public static final SoundEvent ENTITY_CHICKEN_EGG;
    public static final SoundEvent ENTITY_CHICKEN_HURT;
    public static final SoundEvent ENTITY_CHICKEN_STEP;
    public static final SoundEvent BLOCK_CHORUS_FLOWER_DEATH;
    public static final SoundEvent BLOCK_CHORUS_FLOWER_GROW;
    public static final SoundEvent ITEM_CHORUS_FRUIT_TELEPORT;
    public static final SoundEvent BLOCK_WOOL_BREAK;
    public static final SoundEvent BLOCK_WOOL_FALL;
    public static final SoundEvent BLOCK_WOOL_HIT;
    public static final SoundEvent BLOCK_WOOL_PLACE;
    public static final SoundEvent BLOCK_WOOL_STEP;
    public static final SoundEvent BLOCK_COMPARATOR_CLICK;
    public static final SoundEvent ENTITY_COW_AMBIENT;
    public static final SoundEvent ENTITY_COW_DEATH;
    public static final SoundEvent ENTITY_COW_HURT;
    public static final SoundEvent ENTITY_COW_MILK;
    public static final SoundEvent ENTITY_COW_STEP;
    public static final SoundEvent ENTITY_CREEPER_DEATH;
    public static final SoundEvent ENTITY_CREEPER_HURT;
    public static final SoundEvent ENTITY_CREEPER_PRIMED;
    public static final SoundEvent BLOCK_DISPENSER_DISPENSE;
    public static final SoundEvent BLOCK_DISPENSER_FAIL;
    public static final SoundEvent BLOCK_DISPENSER_LAUNCH;
    public static final SoundEvent ENTITY_DONKEY_AMBIENT;
    public static final SoundEvent ENTITY_DONKEY_ANGRY;
    public static final SoundEvent ENTITY_DONKEY_CHEST;
    public static final SoundEvent ENTITY_DONKEY_DEATH;
    public static final SoundEvent ENTITY_DONKEY_HURT;
    public static final SoundEvent ENTITY_EGG_THROW;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_AMBIENT;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_AMBIENT_LAND;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_CURSE;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_DEATH;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_DEATH_LAND;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_FLOP;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_HURT;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_HURT_LAND;
    public static final SoundEvent ITEM_ELYTRA_FLYING;
    public static final SoundEvent BLOCK_ENCHANTMENT_TABLE_USE;
    public static final SoundEvent BLOCK_ENDER_CHEST_CLOSE;
    public static final SoundEvent BLOCK_ENDER_CHEST_OPEN;
    public static final SoundEvent ENTITY_ENDER_DRAGON_AMBIENT;
    public static final SoundEvent ENTITY_ENDER_DRAGON_DEATH;
    public static final SoundEvent ENTITY_DRAGON_FIREBALL_EXPLODE;
    public static final SoundEvent ENTITY_ENDER_DRAGON_FLAP;
    public static final SoundEvent ENTITY_ENDER_DRAGON_GROWL;
    public static final SoundEvent ENTITY_ENDER_DRAGON_HURT;
    public static final SoundEvent ENTITY_ENDER_DRAGON_SHOOT;
    public static final SoundEvent ENTITY_ENDER_EYE_DEATH;
    public static final SoundEvent ENTITY_ENDER_EYE_LAUNCH;
    public static final SoundEvent ENTITY_ENDERMAN_AMBIENT;
    public static final SoundEvent ENTITY_ENDERMAN_DEATH;
    public static final SoundEvent ENTITY_ENDERMAN_HURT;
    public static final SoundEvent ENTITY_ENDERMAN_SCREAM;
    public static final SoundEvent ENTITY_ENDERMAN_STARE;
    public static final SoundEvent ENTITY_ENDERMAN_TELEPORT;
    public static final SoundEvent ENTITY_ENDERMITE_AMBIENT;
    public static final SoundEvent ENTITY_ENDERMITE_DEATH;
    public static final SoundEvent ENTITY_ENDERMITE_HURT;
    public static final SoundEvent ENTITY_ENDERMITE_STEP;
    public static final SoundEvent ENTITY_ENDER_PEARL_THROW;
    public static final SoundEvent BLOCK_END_GATEWAY_SPAWN;
    public static final SoundEvent BLOCK_END_PORTAL_FRAME_FILL;
    public static final SoundEvent BLOCK_END_PORTAL_SPAWN;
    public static final SoundEvent ENTITY_EVOKER_FANGS_ATTACK;
    public static final SoundEvent ENTITY_EVOKER_AMBIENT;
    public static final SoundEvent ENTITY_EVOKER_CAST_SPELL;
    public static final SoundEvent ENTITY_EVOKER_DEATH;
    public static final SoundEvent ENTITY_EVOKER_HURT;
    public static final SoundEvent ENTITY_EVOKER_PREPARE_ATTACK;
    public static final SoundEvent ENTITY_EVOKER_PREPARE_SUMMON;
    public static final SoundEvent ENTITY_EVOKER_PREPARE_WOLOLO;
    public static final SoundEvent ENTITY_EXPERIENCE_BOTTLE_THROW;
    public static final SoundEvent ENTITY_EXPERIENCE_ORB_PICKUP;
    public static final SoundEvent BLOCK_FENCE_GATE_CLOSE;
    public static final SoundEvent BLOCK_FENCE_GATE_OPEN;
    public static final SoundEvent ITEM_FIRECHARGE_USE;
    public static final SoundEvent ENTITY_FIREWORK_ROCKET_BLAST;
    public static final SoundEvent ENTITY_FIREWORK_ROCKET_BLAST_FAR;
    public static final SoundEvent ENTITY_FIREWORK_ROCKET_LARGE_BLAST;
    public static final SoundEvent ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR;
    public static final SoundEvent ENTITY_FIREWORK_ROCKET_LAUNCH;
    public static final SoundEvent ENTITY_FIREWORK_ROCKET_SHOOT;
    public static final SoundEvent ENTITY_FIREWORK_ROCKET_TWINKLE;
    public static final SoundEvent ENTITY_FIREWORK_ROCKET_TWINKLE_FAR;
    public static final SoundEvent BLOCK_FIRE_AMBIENT;
    public static final SoundEvent BLOCK_FIRE_EXTINGUISH;
    public static final SoundEvent ITEM_FLINTANDSTEEL_USE;
    public static final SoundEvent BLOCK_FURNACE_FIRE_CRACKLE;
    public static final SoundEvent ENTITY_GENERIC_BIG_FALL;
    public static final SoundEvent ENTITY_GENERIC_BURN;
    public static final SoundEvent ENTITY_GENERIC_DEATH;
    public static final SoundEvent ENTITY_GENERIC_DRINK;
    public static final SoundEvent ENTITY_GENERIC_EAT;
    public static final SoundEvent ENTITY_GENERIC_EXPLODE;
    public static final SoundEvent ENTITY_GENERIC_EXTINGUISH_FIRE;
    public static final SoundEvent ENTITY_GENERIC_HURT;
    public static final SoundEvent ENTITY_GENERIC_SMALL_FALL;
    public static final SoundEvent ENTITY_GENERIC_SPLASH;
    public static final SoundEvent ENTITY_GENERIC_SWIM;
    public static final SoundEvent ENTITY_GHAST_AMBIENT;
    public static final SoundEvent ENTITY_GHAST_DEATH;
    public static final SoundEvent ENTITY_GHAST_HURT;
    public static final SoundEvent ENTITY_GHAST_SCREAM;
    public static final SoundEvent ENTITY_GHAST_SHOOT;
    public static final SoundEvent ENTITY_GHAST_WARN;
    public static final SoundEvent BLOCK_GLASS_BREAK;
    public static final SoundEvent BLOCK_GLASS_FALL;
    public static final SoundEvent BLOCK_GLASS_HIT;
    public static final SoundEvent BLOCK_GLASS_PLACE;
    public static final SoundEvent BLOCK_GLASS_STEP;
    public static final SoundEvent BLOCK_GRASS_BREAK;
    public static final SoundEvent BLOCK_GRASS_FALL;
    public static final SoundEvent BLOCK_GRASS_HIT;
    public static final SoundEvent BLOCK_GRASS_PLACE;
    public static final SoundEvent BLOCK_GRASS_STEP;
    public static final SoundEvent BLOCK_GRAVEL_BREAK;
    public static final SoundEvent BLOCK_GRAVEL_FALL;
    public static final SoundEvent BLOCK_GRAVEL_HIT;
    public static final SoundEvent BLOCK_GRAVEL_PLACE;
    public static final SoundEvent BLOCK_GRAVEL_STEP;
    public static final SoundEvent ENTITY_GUARDIAN_AMBIENT;
    public static final SoundEvent ENTITY_GUARDIAN_AMBIENT_LAND;
    public static final SoundEvent ENTITY_GUARDIAN_ATTACK;
    public static final SoundEvent ENTITY_GUARDIAN_DEATH;
    public static final SoundEvent ENTITY_GUARDIAN_DEATH_LAND;
    public static final SoundEvent ENTITY_GUARDIAN_FLOP;
    public static final SoundEvent ENTITY_GUARDIAN_HURT;
    public static final SoundEvent ENTITY_GUARDIAN_HURT_LAND;
    public static final SoundEvent ITEM_HOE_TILL;
    public static final SoundEvent ENTITY_HORSE_AMBIENT;
    public static final SoundEvent ENTITY_HORSE_ANGRY;
    public static final SoundEvent ENTITY_HORSE_ARMOR;
    public static final SoundEvent ENTITY_HORSE_BREATHE;
    public static final SoundEvent ENTITY_HORSE_DEATH;
    public static final SoundEvent ENTITY_HORSE_EAT;
    public static final SoundEvent ENTITY_HORSE_GALLOP;
    public static final SoundEvent ENTITY_HORSE_HURT;
    public static final SoundEvent ENTITY_HORSE_JUMP;
    public static final SoundEvent ENTITY_HORSE_LAND;
    public static final SoundEvent ENTITY_HORSE_SADDLE;
    public static final SoundEvent ENTITY_HORSE_STEP;
    public static final SoundEvent ENTITY_HORSE_STEP_WOOD;
    public static final SoundEvent ENTITY_HOSTILE_BIG_FALL;
    public static final SoundEvent ENTITY_HOSTILE_DEATH;
    public static final SoundEvent ENTITY_HOSTILE_HURT;
    public static final SoundEvent ENTITY_HOSTILE_SMALL_FALL;
    public static final SoundEvent ENTITY_HOSTILE_SPLASH;
    public static final SoundEvent ENTITY_HOSTILE_SWIM;
    public static final SoundEvent ENTITY_HUSK_AMBIENT;
    public static final SoundEvent ENTITY_HUSK_DEATH;
    public static final SoundEvent ENTITY_HUSK_HURT;
    public static final SoundEvent ENTITY_HUSK_STEP;
    public static final SoundEvent ENTITY_ILLUSIONER_AMBIENT;
    public static final SoundEvent ENTITY_ILLUSIONER_CAST_SPELL;
    public static final SoundEvent ENTITY_ILLUSIONER_DEATH;
    public static final SoundEvent ENTITY_ILLUSIONER_HURT;
    public static final SoundEvent ENTITY_ILLUSIONER_MIRROR_MOVE;
    public static final SoundEvent ENTITY_ILLUSIONER_PREPARE_BLINDNESS;
    public static final SoundEvent ENTITY_ILLUSIONER_PREPARE_MIRROR;
    public static final SoundEvent ENTITY_IRON_GOLEM_ATTACK;
    public static final SoundEvent ENTITY_IRON_GOLEM_DEATH;
    public static final SoundEvent ENTITY_IRON_GOLEM_HURT;
    public static final SoundEvent ENTITY_IRON_GOLEM_STEP;
    public static final SoundEvent BLOCK_IRON_DOOR_CLOSE;
    public static final SoundEvent BLOCK_IRON_DOOR_OPEN;
    public static final SoundEvent BLOCK_IRON_TRAPDOOR_CLOSE;
    public static final SoundEvent BLOCK_IRON_TRAPDOOR_OPEN;
    public static final SoundEvent ENTITY_ITEM_FRAME_ADD_ITEM;
    public static final SoundEvent ENTITY_ITEM_FRAME_BREAK;
    public static final SoundEvent ENTITY_ITEM_FRAME_PLACE;
    public static final SoundEvent ENTITY_ITEM_FRAME_REMOVE_ITEM;
    public static final SoundEvent ENTITY_ITEM_FRAME_ROTATE_ITEM;
    public static final SoundEvent ENTITY_ITEM_BREAK;
    public static final SoundEvent ENTITY_ITEM_PICKUP;
    public static final SoundEvent BLOCK_LADDER_BREAK;
    public static final SoundEvent BLOCK_LADDER_FALL;
    public static final SoundEvent BLOCK_LADDER_HIT;
    public static final SoundEvent BLOCK_LADDER_PLACE;
    public static final SoundEvent BLOCK_LADDER_STEP;
    public static final SoundEvent BLOCK_LAVA_AMBIENT;
    public static final SoundEvent BLOCK_LAVA_EXTINGUISH;
    public static final SoundEvent BLOCK_LAVA_POP;
    public static final SoundEvent ENTITY_LEASH_KNOT_BREAK;
    public static final SoundEvent ENTITY_LEASH_KNOT_PLACE;
    public static final SoundEvent BLOCK_LEVER_CLICK;
    public static final SoundEvent ENTITY_LIGHTNING_BOLT_IMPACT;
    public static final SoundEvent ENTITY_LIGHTNING_BOLT_THUNDER;
    public static final SoundEvent ENTITY_LINGERING_POTION_THROW;
    public static final SoundEvent ENTITY_LLAMA_AMBIENT;
    public static final SoundEvent ENTITY_LLAMA_ANGRY;
    public static final SoundEvent ENTITY_LLAMA_CHEST;
    public static final SoundEvent ENTITY_LLAMA_DEATH;
    public static final SoundEvent ENTITY_LLAMA_EAT;
    public static final SoundEvent ENTITY_LLAMA_HURT;
    public static final SoundEvent ENTITY_LLAMA_SPIT;
    public static final SoundEvent ENTITY_LLAMA_STEP;
    public static final SoundEvent ENTITY_LLAMA_SWAG;
    public static final SoundEvent ENTITY_MAGMA_CUBE_DEATH;
    public static final SoundEvent ENTITY_MAGMA_CUBE_HURT;
    public static final SoundEvent ENTITY_MAGMA_CUBE_JUMP;
    public static final SoundEvent ENTITY_MAGMA_CUBE_SQUISH;
    public static final SoundEvent BLOCK_METAL_BREAK;
    public static final SoundEvent BLOCK_METAL_FALL;
    public static final SoundEvent BLOCK_METAL_HIT;
    public static final SoundEvent BLOCK_METAL_PLACE;
    public static final SoundEvent BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF;
    public static final SoundEvent BLOCK_METAL_PRESSURE_PLATE_CLICK_ON;
    public static final SoundEvent BLOCK_METAL_STEP;
    public static final SoundEvent ENTITY_MINECART_INSIDE;
    public static final SoundEvent ENTITY_MINECART_RIDING;
    public static final SoundEvent ENTITY_MOOSHROOM_SHEAR;
    public static final SoundEvent ENTITY_MULE_AMBIENT;
    public static final SoundEvent ENTITY_MULE_CHEST;
    public static final SoundEvent ENTITY_MULE_DEATH;
    public static final SoundEvent ENTITY_MULE_HURT;
    public static final SoundEvent MUSIC_CREATIVE;
    public static final SoundEvent MUSIC_CREDITS;
    public static final SoundEvent MUSIC_DRAGON;
    public static final SoundEvent MUSIC_END;
    public static final SoundEvent MUSIC_GAME;
    public static final SoundEvent MUSIC_MENU;
    public static final SoundEvent MUSIC_NETHER;
    public static final SoundEvent BLOCK_NOTE_BLOCK_BASEDRUM;
    public static final SoundEvent BLOCK_NOTE_BLOCK_BASS;
    public static final SoundEvent BLOCK_NOTE_BLOCK_BELL;
    public static final SoundEvent BLOCK_NOTE_BLOCK_CHIME;
    public static final SoundEvent BLOCK_NOTE_BLOCK_FLUTE;
    public static final SoundEvent BLOCK_NOTE_BLOCK_GUITAR;
    public static final SoundEvent BLOCK_NOTE_BLOCK_HARP;
    public static final SoundEvent BLOCK_NOTE_BLOCK_HAT;
    public static final SoundEvent BLOCK_NOTE_BLOCK_PLING;
    public static final SoundEvent BLOCK_NOTE_BLOCK_SNARE;
    public static final SoundEvent BLOCK_NOTE_BLOCK_XYLOPHONE;
    public static final SoundEvent ENTITY_PAINTING_BREAK;
    public static final SoundEvent ENTITY_PAINTING_PLACE;
    public static final SoundEvent ENTITY_PARROT_AMBIENT;
    public static final SoundEvent ENTITY_PARROT_DEATH;
    public static final SoundEvent ENTITY_PARROT_EAT;
    public static final SoundEvent ENTITY_PARROT_FLY;
    public static final SoundEvent ENTITY_PARROT_HURT;
    public static final SoundEvent ENTITY_PARROT_IMITATE_BLAZE;
    public static final SoundEvent ENTITY_PARROT_IMITATE_CREEPER;
    public static final SoundEvent ENTITY_PARROT_IMITATE_ELDER_GUARDIAN;
    public static final SoundEvent ENTITY_PARROT_IMITATE_ENDER_DRAGON;
    public static final SoundEvent field_193795_eQ;
    public static final SoundEvent ENTITY_PARROT_IMITATE_ENDERMITE;
    public static final SoundEvent ENTITY_PARROT_IMITATE_EVOKER;
    public static final SoundEvent ENTITY_PARROT_IMITATE_GHAST;
    public static final SoundEvent ENTITY_PARROT_IMITATE_HUSK;
    public static final SoundEvent ENTITY_PARROT_IMITATE_ILLUSIONER;
    public static final SoundEvent ENTITY_PARROT_IMITATE_MAGMA_CUBE;
    public static final SoundEvent field_193802_eX;
    public static final SoundEvent ENTITY_PARROT_IMITATE_SHULKER;
    public static final SoundEvent ENTITY_PARROT_IMITATE_SILVERFISH;
    public static final SoundEvent ENTITY_PARROT_IMITATE_SKELETON;
    public static final SoundEvent ENTITY_PARROT_IMITATE_SLIME;
    public static final SoundEvent ENTITY_PARROT_IMITATE_SPIDER;
    public static final SoundEvent ENTITY_PARROT_IMITATE_STRAY;
    public static final SoundEvent ENTITY_PARROT_IMITATE_VEX;
    public static final SoundEvent ENTITY_PARROT_IMITATE_VINDICATOR;
    public static final SoundEvent ENTITY_PARROT_IMITATE_WITCH;
    public static final SoundEvent ENTITY_PARROT_IMITATE_WITHER;
    public static final SoundEvent ENTITY_PARROT_IMITATE_WITHER_SKELETON;
    public static final SoundEvent field_193820_fj;
    public static final SoundEvent ENTITY_PARROT_IMITATE_ZOMBIE;
    public static final SoundEvent field_193822_fl;
    public static final SoundEvent ENTITY_PARROT_IMITATE_ZOMBIE_VILLAGER;
    public static final SoundEvent ENTITY_PARROT_STEP;
    public static final SoundEvent ENTITY_PIG_AMBIENT;
    public static final SoundEvent ENTITY_PIG_DEATH;
    public static final SoundEvent ENTITY_PIG_HURT;
    public static final SoundEvent ENTITY_PIG_SADDLE;
    public static final SoundEvent ENTITY_PIG_STEP;
    public static final SoundEvent BLOCK_PISTON_CONTRACT;
    public static final SoundEvent BLOCK_PISTON_EXTEND;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_CRIT;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_KNOCKBACK;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_NODAMAGE;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_STRONG;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_SWEEP;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_WEAK;
    public static final SoundEvent ENTITY_PLAYER_BIG_FALL;
    public static final SoundEvent ENTITY_PLAYER_BREATH;
    public static final SoundEvent ENTITY_PLAYER_BURP;
    public static final SoundEvent ENTITY_PLAYER_DEATH;
    public static final SoundEvent ENTITY_PLAYER_HURT;
    public static final SoundEvent ENTITY_PLAYER_HURT_DROWN;
    public static final SoundEvent ENTITY_PLAYER_HURT_ON_FIRE;
    public static final SoundEvent ENTITY_PLAYER_LEVELUP;
    public static final SoundEvent ENTITY_PLAYER_SMALL_FALL;
    public static final SoundEvent ENTITY_PLAYER_SPLASH;
    public static final SoundEvent ENTITY_PLAYER_SWIM;
    public static final SoundEvent ENTITY_POLAR_BEAR_AMBIENT;
    public static final SoundEvent ENTITY_POLAR_BEAR_AMBIENT_BABY;
    public static final SoundEvent ENTITY_POLAR_BEAR_DEATH;
    public static final SoundEvent ENTITY_POLAR_BEAR_HURT;
    public static final SoundEvent ENTITY_POLAR_BEAR_STEP;
    public static final SoundEvent ENTITY_POLAR_BEAR_WARNING;
    public static final SoundEvent BLOCK_PORTAL_AMBIENT;
    public static final SoundEvent BLOCK_PORTAL_TRAVEL;
    public static final SoundEvent BLOCK_PORTAL_TRIGGER;
    public static final SoundEvent ENTITY_RABBIT_AMBIENT;
    public static final SoundEvent ENTITY_RABBIT_ATTACK;
    public static final SoundEvent ENTITY_RABBIT_DEATH;
    public static final SoundEvent ENTITY_RABBIT_HURT;
    public static final SoundEvent ENTITY_RABBIT_JUMP;
    public static final SoundEvent MUSIC_DISC_11;
    public static final SoundEvent MUSIC_DISC_13;
    public static final SoundEvent MUSIC_DISC_BLOCKS;
    public static final SoundEvent MUSIC_DISC_CAT;
    public static final SoundEvent MUSIC_DISC_CHIRP;
    public static final SoundEvent MUSIC_DISC_FAR;
    public static final SoundEvent MUSIC_DISC_MALL;
    public static final SoundEvent MUSIC_DISC_MELLOHI;
    public static final SoundEvent MUSIC_DISC_STAL;
    public static final SoundEvent MUSIC_DISC_STRAD;
    public static final SoundEvent MUSIC_DISC_WAIT;
    public static final SoundEvent MUSIC_DISC_WARD;
    public static final SoundEvent BLOCK_REDSTONE_TORCH_BURNOUT;
    public static final SoundEvent BLOCK_SAND_BREAK;
    public static final SoundEvent BLOCK_SAND_FALL;
    public static final SoundEvent BLOCK_SAND_HIT;
    public static final SoundEvent BLOCK_SAND_PLACE;
    public static final SoundEvent BLOCK_SAND_STEP;
    public static final SoundEvent ENTITY_SHEEP_AMBIENT;
    public static final SoundEvent ENTITY_SHEEP_DEATH;
    public static final SoundEvent ENTITY_SHEEP_HURT;
    public static final SoundEvent ENTITY_SHEEP_SHEAR;
    public static final SoundEvent ENTITY_SHEEP_STEP;
    public static final SoundEvent ITEM_SHIELD_BLOCK;
    public static final SoundEvent ITEM_SHIELD_BREAK;
    public static final SoundEvent ITEM_SHOVEL_FLATTEN;
    public static final SoundEvent ENTITY_SHULKER_AMBIENT;
    public static final SoundEvent BLOCK_SHULKER_BOX_CLOSE;
    public static final SoundEvent BLOCK_SHULKER_BOX_OPEN;
    public static final SoundEvent ENTITY_SHULKER_BULLET_HIT;
    public static final SoundEvent ENTITY_SHULKER_BULLET_HURT;
    public static final SoundEvent ENTITY_SHULKER_CLOSE;
    public static final SoundEvent ENTITY_SHULKER_DEATH;
    public static final SoundEvent ENTITY_SHULKER_HURT;
    public static final SoundEvent ENTITY_SHULKER_HURT_CLOSED;
    public static final SoundEvent ENTITY_SHULKER_OPEN;
    public static final SoundEvent ENTITY_SHULKER_SHOOT;
    public static final SoundEvent ENTITY_SHULKER_TELEPORT;
    public static final SoundEvent ENTITY_SILVERFISH_AMBIENT;
    public static final SoundEvent ENTITY_SILVERFISH_DEATH;
    public static final SoundEvent ENTITY_SILVERFISH_HURT;
    public static final SoundEvent ENTITY_SILVERFISH_STEP;
    public static final SoundEvent ENTITY_SKELETON_AMBIENT;
    public static final SoundEvent ENTITY_SKELETON_DEATH;
    public static final SoundEvent ENTITY_SKELETON_HORSE_AMBIENT;
    public static final SoundEvent ENTITY_SKELETON_HORSE_DEATH;
    public static final SoundEvent ENTITY_SKELETON_HORSE_HURT;
    public static final SoundEvent ENTITY_SKELETON_HURT;
    public static final SoundEvent ENTITY_SKELETON_SHOOT;
    public static final SoundEvent ENTITY_SKELETON_STEP;
    public static final SoundEvent ENTITY_SLIME_ATTACK;
    public static final SoundEvent BLOCK_SLIME_BLOCK_BREAK;
    public static final SoundEvent ENTITY_SLIME_DEATH;
    public static final SoundEvent BLOCK_SLIME_BLOCK_FALL;
    public static final SoundEvent BLOCK_SLIME_BLOCK_HIT;
    public static final SoundEvent ENTITY_SLIME_HURT;
    public static final SoundEvent ENTITY_SLIME_JUMP;
    public static final SoundEvent BLOCK_SLIME_BLOCK_PLACE;
    public static final SoundEvent ENTITY_SLIME_SQUISH;
    public static final SoundEvent BLOCK_SLIME_BLOCK_STEP;
    public static final SoundEvent ENTITY_MAGMA_CUBE_DEATH_SMALL;
    public static final SoundEvent ENTITY_MAGMA_CUBE_HURT_SMALL;
    public static final SoundEvent ENTITY_MAGMA_CUBE_SQUISH_SMALL;
    public static final SoundEvent ENTITY_SLIME_DEATH_SMALL;
    public static final SoundEvent ENTITY_SLIME_HURT_SMALL;
    public static final SoundEvent ENTITY_SLIME_JUMP_SMALL;
    public static final SoundEvent ENTITY_SLIME_SQUISH_SMALL;
    public static final SoundEvent ENTITY_SNOWBALL_THROW;
    public static final SoundEvent ENTITY_SNOW_GOLEM_AMBIENT;
    public static final SoundEvent ENTITY_SNOW_GOLEM_DEATH;
    public static final SoundEvent ENTITY_SNOW_GOLEM_HURT;
    public static final SoundEvent ENTITY_SNOW_GOLEM_SHOOT;
    public static final SoundEvent BLOCK_SNOW_BREAK;
    public static final SoundEvent BLOCK_SNOW_FALL;
    public static final SoundEvent BLOCK_SNOW_HIT;
    public static final SoundEvent BLOCK_SNOW_PLACE;
    public static final SoundEvent BLOCK_SNOW_STEP;
    public static final SoundEvent ENTITY_SPIDER_AMBIENT;
    public static final SoundEvent ENTITY_SPIDER_DEATH;
    public static final SoundEvent ENTITY_SPIDER_HURT;
    public static final SoundEvent ENTITY_SPIDER_STEP;
    public static final SoundEvent ENTITY_SPLASH_POTION_BREAK;
    public static final SoundEvent ENTITY_SPLASH_POTION_THROW;
    public static final SoundEvent ENTITY_SQUID_AMBIENT;
    public static final SoundEvent ENTITY_SQUID_DEATH;
    public static final SoundEvent ENTITY_SQUID_HURT;
    public static final SoundEvent BLOCK_STONE_BREAK;
    public static final SoundEvent BLOCK_STONE_BUTTON_CLICK_OFF;
    public static final SoundEvent BLOCK_STONE_BUTTON_CLICK_ON;
    public static final SoundEvent BLOCK_STONE_FALL;
    public static final SoundEvent BLOCK_STONE_HIT;
    public static final SoundEvent BLOCK_STONE_PLACE;
    public static final SoundEvent BLOCK_STONE_PRESSURE_PLATE_CLICK_OFF;
    public static final SoundEvent BLOCK_STONE_PRESSURE_PLATE_CLICK_ON;
    public static final SoundEvent BLOCK_STONE_STEP;
    public static final SoundEvent ENTITY_STRAY_AMBIENT;
    public static final SoundEvent ENTITY_STRAY_DEATH;
    public static final SoundEvent ENTITY_STRAY_HURT;
    public static final SoundEvent ENTITY_STRAY_STEP;
    public static final SoundEvent ENCHANT_THORNS_HIT;
    public static final SoundEvent ENTITY_TNT_PRIMED;
    public static final SoundEvent ITEM_TOTEM_USE;
    public static final SoundEvent BLOCK_TRIPWIRE_ATTACH;
    public static final SoundEvent BLOCK_TRIPWIRE_CLICK_OFF;
    public static final SoundEvent BLOCK_TRIPWIRE_CLICK_ON;
    public static final SoundEvent BLOCK_TRIPWIRE_DETACH;
    public static final SoundEvent UI_BUTTON_CLICK;
    public static final SoundEvent UI_TOAST_IN;
    public static final SoundEvent UI_TOAST_OUT;
    public static final SoundEvent UI_TOAST_CHALLENGE_COMPLETE;
    public static final SoundEvent ENTITY_VEX_AMBIENT;
    public static final SoundEvent ENTITY_VEX_CHARGE;
    public static final SoundEvent ENTITY_VEX_DEATH;
    public static final SoundEvent ENTITY_VEX_HURT;
    public static final SoundEvent ENTITY_VILLAGER_AMBIENT;
    public static final SoundEvent ENTITY_VILLAGER_DEATH;
    public static final SoundEvent ENTITY_VILLAGER_HURT;
    public static final SoundEvent ENTITY_VILLAGER_NO;
    public static final SoundEvent ENTITY_VILLAGER_TRADE;
    public static final SoundEvent ENTITY_VILLAGER_YES;
    public static final SoundEvent ENTITY_VINDICATOR_AMBIENT;
    public static final SoundEvent ENTITY_VINDICATOR_DEATH;
    public static final SoundEvent ENTITY_VINDICATOR_HURT;
    public static final SoundEvent BLOCK_LILY_PAD_PLACE;
    public static final SoundEvent BLOCK_WATER_AMBIENT;
    public static final SoundEvent WEATHER_RAIN;
    public static final SoundEvent WEATHER_RAIN_ABOVE;
    public static final SoundEvent ENTITY_WITCH_AMBIENT;
    public static final SoundEvent ENTITY_WITCH_DEATH;
    public static final SoundEvent ENTITY_WITCH_DRINK;
    public static final SoundEvent ENTITY_WITCH_HURT;
    public static final SoundEvent ENTITY_WITCH_THROW;
    public static final SoundEvent ENTITY_WITHER_AMBIENT;
    public static final SoundEvent ENTITY_WITHER_BREAK_BLOCK;
    public static final SoundEvent ENTITY_WITHER_DEATH;
    public static final SoundEvent ENTITY_WITHER_HURT;
    public static final SoundEvent ENTITY_WITHER_SHOOT;
    public static final SoundEvent ENTITY_WITHER_SKELETON_AMBIENT;
    public static final SoundEvent ENTITY_WITHER_SKELETON_DEATH;
    public static final SoundEvent ENTITY_WITHER_SKELETON_HURT;
    public static final SoundEvent ENTITY_WITHER_SKELETON_STEP;
    public static final SoundEvent ENTITY_WITHER_SPAWN;
    public static final SoundEvent ENTITY_WOLF_AMBIENT;
    public static final SoundEvent ENTITY_WOLF_DEATH;
    public static final SoundEvent ENTITY_WOLF_GROWL;
    public static final SoundEvent ENTITY_WOLF_HOWL;
    public static final SoundEvent ENTITY_WOLF_HURT;
    public static final SoundEvent ENTITY_WOLF_PANT;
    public static final SoundEvent ENTITY_WOLF_SHAKE;
    public static final SoundEvent ENTITY_WOLF_STEP;
    public static final SoundEvent ENTITY_WOLF_WHINE;
    public static final SoundEvent BLOCK_WOODEN_DOOR_CLOSE;
    public static final SoundEvent BLOCK_WOODEN_DOOR_OPEN;
    public static final SoundEvent BLOCK_WOODEN_TRAPDOOR_CLOSE;
    public static final SoundEvent BLOCK_WOODEN_TRAPDOOR_OPEN;
    public static final SoundEvent BLOCK_WOOD_BREAK;
    public static final SoundEvent BLOCK_WOODEN_BUTTON_CLICK_OFF;
    public static final SoundEvent BLOCK_WOODEN_BUTTON_CLICK_ON;
    public static final SoundEvent BLOCK_WOOD_FALL;
    public static final SoundEvent BLOCK_WOOD_HIT;
    public static final SoundEvent BLOCK_WOOD_PLACE;
    public static final SoundEvent BLOCK_WOODEN_PRESSURE_PLATE_CLICK_OFF;
    public static final SoundEvent BLOCK_WOODEN_PRESSURE_PLATE_CLICK_ON;
    public static final SoundEvent BLOCK_WOOD_STEP;
    public static final SoundEvent ENTITY_ZOMBIE_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR;
    public static final SoundEvent ENTITY_ZOMBIE_ATTACK_IRON_DOOR;
    public static final SoundEvent ENTITY_ZOMBIE_BREAK_WOODEN_DOOR;
    public static final SoundEvent ENTITY_ZOMBIE_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_HORSE_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_HORSE_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_HORSE_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_INFECT;
    public static final SoundEvent ENTITY_ZOMBIE_PIGMAN_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_PIGMAN_ANGRY;
    public static final SoundEvent ENTITY_ZOMBIE_PIGMAN_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_PIGMAN_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_STEP;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_CONVERTED;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_CURE;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_STEP;

    private static SoundEvent func_187510_a(String p_187510_0_)
    {
        SoundEvent soundevent = SoundEvent.field_187505_a.getOrDefault(new ResourceLocation(p_187510_0_));

        if (soundevent == null)
        {
            throw new IllegalStateException("Invalid Sound requested: " + p_187510_0_);
        }
        else
        {
            return soundevent;
        }
    }

    static
    {
        if (!Bootstrap.func_179869_a())
        {
            throw new RuntimeException("Accessed Sounds before Bootstrap!");
        }
        else
        {
            AMBIENT_CAVE = func_187510_a("ambient.cave");
            BLOCK_ANVIL_BREAK = func_187510_a("block.anvil.break");
            BLOCK_ANVIL_DESTROY = func_187510_a("block.anvil.destroy");
            BLOCK_ANVIL_FALL = func_187510_a("block.anvil.fall");
            BLOCK_ANVIL_HIT = func_187510_a("block.anvil.hit");
            BLOCK_ANVIL_LAND = func_187510_a("block.anvil.land");
            BLOCK_ANVIL_PLACE = func_187510_a("block.anvil.place");
            BLOCK_ANVIL_STEP = func_187510_a("block.anvil.step");
            BLOCK_ANVIL_USE = func_187510_a("block.anvil.use");
            ENTITY_ARMOR_STAND_BREAK = func_187510_a("entity.armorstand.break");
            ENTITY_ARMOR_STAND_FALL = func_187510_a("entity.armorstand.fall");
            ENTITY_ARMOR_STAND_HIT = func_187510_a("entity.armorstand.hit");
            ENTITY_ARMOR_STAND_PLACE = func_187510_a("entity.armorstand.place");
            ITEM_ARMOR_EQUIP_CHAIN = func_187510_a("item.armor.equip_chain");
            ITEM_ARMOR_EQUIP_DIAMOND = func_187510_a("item.armor.equip_diamond");
            ITEM_ARMOR_EQUIP_ELYTRA = func_187510_a("item.armor.equip_elytra");
            ITEM_ARMOR_EQUIP_GENERIC = func_187510_a("item.armor.equip_generic");
            ITEM_ARMOR_EQUIP_GOLD = func_187510_a("item.armor.equip_gold");
            ITEM_ARMOR_EQUIP_IRON = func_187510_a("item.armor.equip_iron");
            ITEM_ARMOR_EQUIP_LEATHER = func_187510_a("item.armor.equip_leather");
            ENTITY_ARROW_HIT = func_187510_a("entity.arrow.hit");
            ENTITY_ARROW_HIT_PLAYER = func_187510_a("entity.arrow.hit_player");
            ENTITY_ARROW_SHOOT = func_187510_a("entity.arrow.shoot");
            ENTITY_BAT_AMBIENT = func_187510_a("entity.bat.ambient");
            ENTITY_BAT_DEATH = func_187510_a("entity.bat.death");
            ENTITY_BAT_HURT = func_187510_a("entity.bat.hurt");
            ENTITY_BAT_LOOP = func_187510_a("entity.bat.loop");
            ENTITY_BAT_TAKEOFF = func_187510_a("entity.bat.takeoff");
            ENTITY_BLAZE_AMBIENT = func_187510_a("entity.blaze.ambient");
            ENTITY_BLAZE_BURN = func_187510_a("entity.blaze.burn");
            ENTITY_BLAZE_DEATH = func_187510_a("entity.blaze.death");
            ENTITY_BLAZE_HURT = func_187510_a("entity.blaze.hurt");
            ENTITY_BLAZE_SHOOT = func_187510_a("entity.blaze.shoot");
            ENTITY_BOAT_PADDLE_LAND = func_187510_a("entity.boat.paddle_land");
            ENTITY_BOAT_PADDLE_WATER = func_187510_a("entity.boat.paddle_water");
            ENTITY_FISHING_BOBBER_RETRIEVE = func_187510_a("entity.bobber.retrieve");
            ENTITY_FISHING_BOBBER_SPLASH = func_187510_a("entity.bobber.splash");
            ENTITY_FISHING_BOBBER_THROW = func_187510_a("entity.bobber.throw");
            ITEM_BOTTLE_EMPTY = func_187510_a("item.bottle.empty");
            ITEM_BOTTLE_FILL = func_187510_a("item.bottle.fill");
            ITEM_BOTTLE_FILL_DRAGONBREATH = func_187510_a("item.bottle.fill_dragonbreath");
            BLOCK_BREWING_STAND_BREW = func_187510_a("block.brewing_stand.brew");
            ITEM_BUCKET_EMPTY = func_187510_a("item.bucket.empty");
            ITEM_BUCKET_EMPTY_LAVA = func_187510_a("item.bucket.empty_lava");
            ITEM_BUCKET_FILL = func_187510_a("item.bucket.fill");
            ITEM_BUCKET_FILL_LAVA = func_187510_a("item.bucket.fill_lava");
            ENTITY_CAT_AMBIENT = func_187510_a("entity.cat.ambient");
            ENTITY_CAT_DEATH = func_187510_a("entity.cat.death");
            ENTITY_CAT_HISS = func_187510_a("entity.cat.hiss");
            ENTITY_CAT_HURT = func_187510_a("entity.cat.hurt");
            ENTITY_CAT_PURR = func_187510_a("entity.cat.purr");
            ENTITY_CAT_PURREOW = func_187510_a("entity.cat.purreow");
            BLOCK_CHEST_CLOSE = func_187510_a("block.chest.close");
            BLOCK_CHEST_LOCKED = func_187510_a("block.chest.locked");
            BLOCK_CHEST_OPEN = func_187510_a("block.chest.open");
            ENTITY_CHICKEN_AMBIENT = func_187510_a("entity.chicken.ambient");
            ENTITY_CHICKEN_DEATH = func_187510_a("entity.chicken.death");
            ENTITY_CHICKEN_EGG = func_187510_a("entity.chicken.egg");
            ENTITY_CHICKEN_HURT = func_187510_a("entity.chicken.hurt");
            ENTITY_CHICKEN_STEP = func_187510_a("entity.chicken.step");
            BLOCK_CHORUS_FLOWER_DEATH = func_187510_a("block.chorus_flower.death");
            BLOCK_CHORUS_FLOWER_GROW = func_187510_a("block.chorus_flower.grow");
            ITEM_CHORUS_FRUIT_TELEPORT = func_187510_a("item.chorus_fruit.teleport");
            BLOCK_WOOL_BREAK = func_187510_a("block.cloth.break");
            BLOCK_WOOL_FALL = func_187510_a("block.cloth.fall");
            BLOCK_WOOL_HIT = func_187510_a("block.cloth.hit");
            BLOCK_WOOL_PLACE = func_187510_a("block.cloth.place");
            BLOCK_WOOL_STEP = func_187510_a("block.cloth.step");
            BLOCK_COMPARATOR_CLICK = func_187510_a("block.comparator.click");
            ENTITY_COW_AMBIENT = func_187510_a("entity.cow.ambient");
            ENTITY_COW_DEATH = func_187510_a("entity.cow.death");
            ENTITY_COW_HURT = func_187510_a("entity.cow.hurt");
            ENTITY_COW_MILK = func_187510_a("entity.cow.milk");
            ENTITY_COW_STEP = func_187510_a("entity.cow.step");
            ENTITY_CREEPER_DEATH = func_187510_a("entity.creeper.death");
            ENTITY_CREEPER_HURT = func_187510_a("entity.creeper.hurt");
            ENTITY_CREEPER_PRIMED = func_187510_a("entity.creeper.primed");
            BLOCK_DISPENSER_DISPENSE = func_187510_a("block.dispenser.dispense");
            BLOCK_DISPENSER_FAIL = func_187510_a("block.dispenser.fail");
            BLOCK_DISPENSER_LAUNCH = func_187510_a("block.dispenser.launch");
            ENTITY_DONKEY_AMBIENT = func_187510_a("entity.donkey.ambient");
            ENTITY_DONKEY_ANGRY = func_187510_a("entity.donkey.angry");
            ENTITY_DONKEY_CHEST = func_187510_a("entity.donkey.chest");
            ENTITY_DONKEY_DEATH = func_187510_a("entity.donkey.death");
            ENTITY_DONKEY_HURT = func_187510_a("entity.donkey.hurt");
            ENTITY_EGG_THROW = func_187510_a("entity.egg.throw");
            ENTITY_ELDER_GUARDIAN_AMBIENT = func_187510_a("entity.elder_guardian.ambient");
            ENTITY_ELDER_GUARDIAN_AMBIENT_LAND = func_187510_a("entity.elder_guardian.ambient_land");
            ENTITY_ELDER_GUARDIAN_CURSE = func_187510_a("entity.elder_guardian.curse");
            ENTITY_ELDER_GUARDIAN_DEATH = func_187510_a("entity.elder_guardian.death");
            ENTITY_ELDER_GUARDIAN_DEATH_LAND = func_187510_a("entity.elder_guardian.death_land");
            ENTITY_ELDER_GUARDIAN_FLOP = func_187510_a("entity.elder_guardian.flop");
            ENTITY_ELDER_GUARDIAN_HURT = func_187510_a("entity.elder_guardian.hurt");
            ENTITY_ELDER_GUARDIAN_HURT_LAND = func_187510_a("entity.elder_guardian.hurt_land");
            ITEM_ELYTRA_FLYING = func_187510_a("item.elytra.flying");
            BLOCK_ENCHANTMENT_TABLE_USE = func_187510_a("block.enchantment_table.use");
            BLOCK_ENDER_CHEST_CLOSE = func_187510_a("block.enderchest.close");
            BLOCK_ENDER_CHEST_OPEN = func_187510_a("block.enderchest.open");
            ENTITY_ENDER_DRAGON_AMBIENT = func_187510_a("entity.enderdragon.ambient");
            ENTITY_ENDER_DRAGON_DEATH = func_187510_a("entity.enderdragon.death");
            ENTITY_DRAGON_FIREBALL_EXPLODE = func_187510_a("entity.enderdragon_fireball.explode");
            ENTITY_ENDER_DRAGON_FLAP = func_187510_a("entity.enderdragon.flap");
            ENTITY_ENDER_DRAGON_GROWL = func_187510_a("entity.enderdragon.growl");
            ENTITY_ENDER_DRAGON_HURT = func_187510_a("entity.enderdragon.hurt");
            ENTITY_ENDER_DRAGON_SHOOT = func_187510_a("entity.enderdragon.shoot");
            ENTITY_ENDER_EYE_DEATH = func_187510_a("entity.endereye.death");
            ENTITY_ENDER_EYE_LAUNCH = func_187510_a("entity.endereye.launch");
            ENTITY_ENDERMAN_AMBIENT = func_187510_a("entity.endermen.ambient");
            ENTITY_ENDERMAN_DEATH = func_187510_a("entity.endermen.death");
            ENTITY_ENDERMAN_HURT = func_187510_a("entity.endermen.hurt");
            ENTITY_ENDERMAN_SCREAM = func_187510_a("entity.endermen.scream");
            ENTITY_ENDERMAN_STARE = func_187510_a("entity.endermen.stare");
            ENTITY_ENDERMAN_TELEPORT = func_187510_a("entity.endermen.teleport");
            ENTITY_ENDERMITE_AMBIENT = func_187510_a("entity.endermite.ambient");
            ENTITY_ENDERMITE_DEATH = func_187510_a("entity.endermite.death");
            ENTITY_ENDERMITE_HURT = func_187510_a("entity.endermite.hurt");
            ENTITY_ENDERMITE_STEP = func_187510_a("entity.endermite.step");
            ENTITY_ENDER_PEARL_THROW = func_187510_a("entity.enderpearl.throw");
            BLOCK_END_GATEWAY_SPAWN = func_187510_a("block.end_gateway.spawn");
            BLOCK_END_PORTAL_FRAME_FILL = func_187510_a("block.end_portal_frame.fill");
            BLOCK_END_PORTAL_SPAWN = func_187510_a("block.end_portal.spawn");
            ENTITY_EVOKER_FANGS_ATTACK = func_187510_a("entity.evocation_fangs.attack");
            ENTITY_EVOKER_AMBIENT = func_187510_a("entity.evocation_illager.ambient");
            ENTITY_EVOKER_CAST_SPELL = func_187510_a("entity.evocation_illager.cast_spell");
            ENTITY_EVOKER_DEATH = func_187510_a("entity.evocation_illager.death");
            ENTITY_EVOKER_HURT = func_187510_a("entity.evocation_illager.hurt");
            ENTITY_EVOKER_PREPARE_ATTACK = func_187510_a("entity.evocation_illager.prepare_attack");
            ENTITY_EVOKER_PREPARE_SUMMON = func_187510_a("entity.evocation_illager.prepare_summon");
            ENTITY_EVOKER_PREPARE_WOLOLO = func_187510_a("entity.evocation_illager.prepare_wololo");
            ENTITY_EXPERIENCE_BOTTLE_THROW = func_187510_a("entity.experience_bottle.throw");
            ENTITY_EXPERIENCE_ORB_PICKUP = func_187510_a("entity.experience_orb.pickup");
            BLOCK_FENCE_GATE_CLOSE = func_187510_a("block.fence_gate.close");
            BLOCK_FENCE_GATE_OPEN = func_187510_a("block.fence_gate.open");
            ITEM_FIRECHARGE_USE = func_187510_a("item.firecharge.use");
            ENTITY_FIREWORK_ROCKET_BLAST = func_187510_a("entity.firework.blast");
            ENTITY_FIREWORK_ROCKET_BLAST_FAR = func_187510_a("entity.firework.blast_far");
            ENTITY_FIREWORK_ROCKET_LARGE_BLAST = func_187510_a("entity.firework.large_blast");
            ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR = func_187510_a("entity.firework.large_blast_far");
            ENTITY_FIREWORK_ROCKET_LAUNCH = func_187510_a("entity.firework.launch");
            ENTITY_FIREWORK_ROCKET_SHOOT = func_187510_a("entity.firework.shoot");
            ENTITY_FIREWORK_ROCKET_TWINKLE = func_187510_a("entity.firework.twinkle");
            ENTITY_FIREWORK_ROCKET_TWINKLE_FAR = func_187510_a("entity.firework.twinkle_far");
            BLOCK_FIRE_AMBIENT = func_187510_a("block.fire.ambient");
            BLOCK_FIRE_EXTINGUISH = func_187510_a("block.fire.extinguish");
            ITEM_FLINTANDSTEEL_USE = func_187510_a("item.flintandsteel.use");
            BLOCK_FURNACE_FIRE_CRACKLE = func_187510_a("block.furnace.fire_crackle");
            ENTITY_GENERIC_BIG_FALL = func_187510_a("entity.generic.big_fall");
            ENTITY_GENERIC_BURN = func_187510_a("entity.generic.burn");
            ENTITY_GENERIC_DEATH = func_187510_a("entity.generic.death");
            ENTITY_GENERIC_DRINK = func_187510_a("entity.generic.drink");
            ENTITY_GENERIC_EAT = func_187510_a("entity.generic.eat");
            ENTITY_GENERIC_EXPLODE = func_187510_a("entity.generic.explode");
            ENTITY_GENERIC_EXTINGUISH_FIRE = func_187510_a("entity.generic.extinguish_fire");
            ENTITY_GENERIC_HURT = func_187510_a("entity.generic.hurt");
            ENTITY_GENERIC_SMALL_FALL = func_187510_a("entity.generic.small_fall");
            ENTITY_GENERIC_SPLASH = func_187510_a("entity.generic.splash");
            ENTITY_GENERIC_SWIM = func_187510_a("entity.generic.swim");
            ENTITY_GHAST_AMBIENT = func_187510_a("entity.ghast.ambient");
            ENTITY_GHAST_DEATH = func_187510_a("entity.ghast.death");
            ENTITY_GHAST_HURT = func_187510_a("entity.ghast.hurt");
            ENTITY_GHAST_SCREAM = func_187510_a("entity.ghast.scream");
            ENTITY_GHAST_SHOOT = func_187510_a("entity.ghast.shoot");
            ENTITY_GHAST_WARN = func_187510_a("entity.ghast.warn");
            BLOCK_GLASS_BREAK = func_187510_a("block.glass.break");
            BLOCK_GLASS_FALL = func_187510_a("block.glass.fall");
            BLOCK_GLASS_HIT = func_187510_a("block.glass.hit");
            BLOCK_GLASS_PLACE = func_187510_a("block.glass.place");
            BLOCK_GLASS_STEP = func_187510_a("block.glass.step");
            BLOCK_GRASS_BREAK = func_187510_a("block.grass.break");
            BLOCK_GRASS_FALL = func_187510_a("block.grass.fall");
            BLOCK_GRASS_HIT = func_187510_a("block.grass.hit");
            BLOCK_GRASS_PLACE = func_187510_a("block.grass.place");
            BLOCK_GRASS_STEP = func_187510_a("block.grass.step");
            BLOCK_GRAVEL_BREAK = func_187510_a("block.gravel.break");
            BLOCK_GRAVEL_FALL = func_187510_a("block.gravel.fall");
            BLOCK_GRAVEL_HIT = func_187510_a("block.gravel.hit");
            BLOCK_GRAVEL_PLACE = func_187510_a("block.gravel.place");
            BLOCK_GRAVEL_STEP = func_187510_a("block.gravel.step");
            ENTITY_GUARDIAN_AMBIENT = func_187510_a("entity.guardian.ambient");
            ENTITY_GUARDIAN_AMBIENT_LAND = func_187510_a("entity.guardian.ambient_land");
            ENTITY_GUARDIAN_ATTACK = func_187510_a("entity.guardian.attack");
            ENTITY_GUARDIAN_DEATH = func_187510_a("entity.guardian.death");
            ENTITY_GUARDIAN_DEATH_LAND = func_187510_a("entity.guardian.death_land");
            ENTITY_GUARDIAN_FLOP = func_187510_a("entity.guardian.flop");
            ENTITY_GUARDIAN_HURT = func_187510_a("entity.guardian.hurt");
            ENTITY_GUARDIAN_HURT_LAND = func_187510_a("entity.guardian.hurt_land");
            ITEM_HOE_TILL = func_187510_a("item.hoe.till");
            ENTITY_HORSE_AMBIENT = func_187510_a("entity.horse.ambient");
            ENTITY_HORSE_ANGRY = func_187510_a("entity.horse.angry");
            ENTITY_HORSE_ARMOR = func_187510_a("entity.horse.armor");
            ENTITY_HORSE_BREATHE = func_187510_a("entity.horse.breathe");
            ENTITY_HORSE_DEATH = func_187510_a("entity.horse.death");
            ENTITY_HORSE_EAT = func_187510_a("entity.horse.eat");
            ENTITY_HORSE_GALLOP = func_187510_a("entity.horse.gallop");
            ENTITY_HORSE_HURT = func_187510_a("entity.horse.hurt");
            ENTITY_HORSE_JUMP = func_187510_a("entity.horse.jump");
            ENTITY_HORSE_LAND = func_187510_a("entity.horse.land");
            ENTITY_HORSE_SADDLE = func_187510_a("entity.horse.saddle");
            ENTITY_HORSE_STEP = func_187510_a("entity.horse.step");
            ENTITY_HORSE_STEP_WOOD = func_187510_a("entity.horse.step_wood");
            ENTITY_HOSTILE_BIG_FALL = func_187510_a("entity.hostile.big_fall");
            ENTITY_HOSTILE_DEATH = func_187510_a("entity.hostile.death");
            ENTITY_HOSTILE_HURT = func_187510_a("entity.hostile.hurt");
            ENTITY_HOSTILE_SMALL_FALL = func_187510_a("entity.hostile.small_fall");
            ENTITY_HOSTILE_SPLASH = func_187510_a("entity.hostile.splash");
            ENTITY_HOSTILE_SWIM = func_187510_a("entity.hostile.swim");
            ENTITY_HUSK_AMBIENT = func_187510_a("entity.husk.ambient");
            ENTITY_HUSK_DEATH = func_187510_a("entity.husk.death");
            ENTITY_HUSK_HURT = func_187510_a("entity.husk.hurt");
            ENTITY_HUSK_STEP = func_187510_a("entity.husk.step");
            ENTITY_ILLUSIONER_AMBIENT = func_187510_a("entity.illusion_illager.ambient");
            ENTITY_ILLUSIONER_CAST_SPELL = func_187510_a("entity.illusion_illager.cast_spell");
            ENTITY_ILLUSIONER_DEATH = func_187510_a("entity.illusion_illager.death");
            ENTITY_ILLUSIONER_HURT = func_187510_a("entity.illusion_illager.hurt");
            ENTITY_ILLUSIONER_MIRROR_MOVE = func_187510_a("entity.illusion_illager.mirror_move");
            ENTITY_ILLUSIONER_PREPARE_BLINDNESS = func_187510_a("entity.illusion_illager.prepare_blindness");
            ENTITY_ILLUSIONER_PREPARE_MIRROR = func_187510_a("entity.illusion_illager.prepare_mirror");
            ENTITY_IRON_GOLEM_ATTACK = func_187510_a("entity.irongolem.attack");
            ENTITY_IRON_GOLEM_DEATH = func_187510_a("entity.irongolem.death");
            ENTITY_IRON_GOLEM_HURT = func_187510_a("entity.irongolem.hurt");
            ENTITY_IRON_GOLEM_STEP = func_187510_a("entity.irongolem.step");
            BLOCK_IRON_DOOR_CLOSE = func_187510_a("block.iron_door.close");
            BLOCK_IRON_DOOR_OPEN = func_187510_a("block.iron_door.open");
            BLOCK_IRON_TRAPDOOR_CLOSE = func_187510_a("block.iron_trapdoor.close");
            BLOCK_IRON_TRAPDOOR_OPEN = func_187510_a("block.iron_trapdoor.open");
            ENTITY_ITEM_FRAME_ADD_ITEM = func_187510_a("entity.itemframe.add_item");
            ENTITY_ITEM_FRAME_BREAK = func_187510_a("entity.itemframe.break");
            ENTITY_ITEM_FRAME_PLACE = func_187510_a("entity.itemframe.place");
            ENTITY_ITEM_FRAME_REMOVE_ITEM = func_187510_a("entity.itemframe.remove_item");
            ENTITY_ITEM_FRAME_ROTATE_ITEM = func_187510_a("entity.itemframe.rotate_item");
            ENTITY_ITEM_BREAK = func_187510_a("entity.item.break");
            ENTITY_ITEM_PICKUP = func_187510_a("entity.item.pickup");
            BLOCK_LADDER_BREAK = func_187510_a("block.ladder.break");
            BLOCK_LADDER_FALL = func_187510_a("block.ladder.fall");
            BLOCK_LADDER_HIT = func_187510_a("block.ladder.hit");
            BLOCK_LADDER_PLACE = func_187510_a("block.ladder.place");
            BLOCK_LADDER_STEP = func_187510_a("block.ladder.step");
            BLOCK_LAVA_AMBIENT = func_187510_a("block.lava.ambient");
            BLOCK_LAVA_EXTINGUISH = func_187510_a("block.lava.extinguish");
            BLOCK_LAVA_POP = func_187510_a("block.lava.pop");
            ENTITY_LEASH_KNOT_BREAK = func_187510_a("entity.leashknot.break");
            ENTITY_LEASH_KNOT_PLACE = func_187510_a("entity.leashknot.place");
            BLOCK_LEVER_CLICK = func_187510_a("block.lever.click");
            ENTITY_LIGHTNING_BOLT_IMPACT = func_187510_a("entity.lightning.impact");
            ENTITY_LIGHTNING_BOLT_THUNDER = func_187510_a("entity.lightning.thunder");
            ENTITY_LINGERING_POTION_THROW = func_187510_a("entity.lingeringpotion.throw");
            ENTITY_LLAMA_AMBIENT = func_187510_a("entity.llama.ambient");
            ENTITY_LLAMA_ANGRY = func_187510_a("entity.llama.angry");
            ENTITY_LLAMA_CHEST = func_187510_a("entity.llama.chest");
            ENTITY_LLAMA_DEATH = func_187510_a("entity.llama.death");
            ENTITY_LLAMA_EAT = func_187510_a("entity.llama.eat");
            ENTITY_LLAMA_HURT = func_187510_a("entity.llama.hurt");
            ENTITY_LLAMA_SPIT = func_187510_a("entity.llama.spit");
            ENTITY_LLAMA_STEP = func_187510_a("entity.llama.step");
            ENTITY_LLAMA_SWAG = func_187510_a("entity.llama.swag");
            ENTITY_MAGMA_CUBE_DEATH = func_187510_a("entity.magmacube.death");
            ENTITY_MAGMA_CUBE_HURT = func_187510_a("entity.magmacube.hurt");
            ENTITY_MAGMA_CUBE_JUMP = func_187510_a("entity.magmacube.jump");
            ENTITY_MAGMA_CUBE_SQUISH = func_187510_a("entity.magmacube.squish");
            BLOCK_METAL_BREAK = func_187510_a("block.metal.break");
            BLOCK_METAL_FALL = func_187510_a("block.metal.fall");
            BLOCK_METAL_HIT = func_187510_a("block.metal.hit");
            BLOCK_METAL_PLACE = func_187510_a("block.metal.place");
            BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF = func_187510_a("block.metal_pressureplate.click_off");
            BLOCK_METAL_PRESSURE_PLATE_CLICK_ON = func_187510_a("block.metal_pressureplate.click_on");
            BLOCK_METAL_STEP = func_187510_a("block.metal.step");
            ENTITY_MINECART_INSIDE = func_187510_a("entity.minecart.inside");
            ENTITY_MINECART_RIDING = func_187510_a("entity.minecart.riding");
            ENTITY_MOOSHROOM_SHEAR = func_187510_a("entity.mooshroom.shear");
            ENTITY_MULE_AMBIENT = func_187510_a("entity.mule.ambient");
            ENTITY_MULE_CHEST = func_187510_a("entity.mule.chest");
            ENTITY_MULE_DEATH = func_187510_a("entity.mule.death");
            ENTITY_MULE_HURT = func_187510_a("entity.mule.hurt");
            MUSIC_CREATIVE = func_187510_a("music.creative");
            MUSIC_CREDITS = func_187510_a("music.credits");
            MUSIC_DRAGON = func_187510_a("music.dragon");
            MUSIC_END = func_187510_a("music.end");
            MUSIC_GAME = func_187510_a("music.game");
            MUSIC_MENU = func_187510_a("music.menu");
            MUSIC_NETHER = func_187510_a("music.nether");
            BLOCK_NOTE_BLOCK_BASEDRUM = func_187510_a("block.note.basedrum");
            BLOCK_NOTE_BLOCK_BASS = func_187510_a("block.note.bass");
            BLOCK_NOTE_BLOCK_BELL = func_187510_a("block.note.bell");
            BLOCK_NOTE_BLOCK_CHIME = func_187510_a("block.note.chime");
            BLOCK_NOTE_BLOCK_FLUTE = func_187510_a("block.note.flute");
            BLOCK_NOTE_BLOCK_GUITAR = func_187510_a("block.note.guitar");
            BLOCK_NOTE_BLOCK_HARP = func_187510_a("block.note.harp");
            BLOCK_NOTE_BLOCK_HAT = func_187510_a("block.note.hat");
            BLOCK_NOTE_BLOCK_PLING = func_187510_a("block.note.pling");
            BLOCK_NOTE_BLOCK_SNARE = func_187510_a("block.note.snare");
            BLOCK_NOTE_BLOCK_XYLOPHONE = func_187510_a("block.note.xylophone");
            ENTITY_PAINTING_BREAK = func_187510_a("entity.painting.break");
            ENTITY_PAINTING_PLACE = func_187510_a("entity.painting.place");
            ENTITY_PARROT_AMBIENT = func_187510_a("entity.parrot.ambient");
            ENTITY_PARROT_DEATH = func_187510_a("entity.parrot.death");
            ENTITY_PARROT_EAT = func_187510_a("entity.parrot.eat");
            ENTITY_PARROT_FLY = func_187510_a("entity.parrot.fly");
            ENTITY_PARROT_HURT = func_187510_a("entity.parrot.hurt");
            ENTITY_PARROT_IMITATE_BLAZE = func_187510_a("entity.parrot.imitate.blaze");
            ENTITY_PARROT_IMITATE_CREEPER = func_187510_a("entity.parrot.imitate.creeper");
            ENTITY_PARROT_IMITATE_ELDER_GUARDIAN = func_187510_a("entity.parrot.imitate.elder_guardian");
            ENTITY_PARROT_IMITATE_ENDER_DRAGON = func_187510_a("entity.parrot.imitate.enderdragon");
            field_193795_eQ = func_187510_a("entity.parrot.imitate.enderman");
            ENTITY_PARROT_IMITATE_ENDERMITE = func_187510_a("entity.parrot.imitate.endermite");
            ENTITY_PARROT_IMITATE_EVOKER = func_187510_a("entity.parrot.imitate.evocation_illager");
            ENTITY_PARROT_IMITATE_GHAST = func_187510_a("entity.parrot.imitate.ghast");
            ENTITY_PARROT_IMITATE_HUSK = func_187510_a("entity.parrot.imitate.husk");
            ENTITY_PARROT_IMITATE_ILLUSIONER = func_187510_a("entity.parrot.imitate.illusion_illager");
            ENTITY_PARROT_IMITATE_MAGMA_CUBE = func_187510_a("entity.parrot.imitate.magmacube");
            field_193802_eX = func_187510_a("entity.parrot.imitate.polar_bear");
            ENTITY_PARROT_IMITATE_SHULKER = func_187510_a("entity.parrot.imitate.shulker");
            ENTITY_PARROT_IMITATE_SILVERFISH = func_187510_a("entity.parrot.imitate.silverfish");
            ENTITY_PARROT_IMITATE_SKELETON = func_187510_a("entity.parrot.imitate.skeleton");
            ENTITY_PARROT_IMITATE_SLIME = func_187510_a("entity.parrot.imitate.slime");
            ENTITY_PARROT_IMITATE_SPIDER = func_187510_a("entity.parrot.imitate.spider");
            ENTITY_PARROT_IMITATE_STRAY = func_187510_a("entity.parrot.imitate.stray");
            ENTITY_PARROT_IMITATE_VEX = func_187510_a("entity.parrot.imitate.vex");
            ENTITY_PARROT_IMITATE_VINDICATOR = func_187510_a("entity.parrot.imitate.vindication_illager");
            ENTITY_PARROT_IMITATE_WITCH = func_187510_a("entity.parrot.imitate.witch");
            ENTITY_PARROT_IMITATE_WITHER = func_187510_a("entity.parrot.imitate.wither");
            ENTITY_PARROT_IMITATE_WITHER_SKELETON = func_187510_a("entity.parrot.imitate.wither_skeleton");
            field_193820_fj = func_187510_a("entity.parrot.imitate.wolf");
            ENTITY_PARROT_IMITATE_ZOMBIE = func_187510_a("entity.parrot.imitate.zombie");
            field_193822_fl = func_187510_a("entity.parrot.imitate.zombie_pigman");
            ENTITY_PARROT_IMITATE_ZOMBIE_VILLAGER = func_187510_a("entity.parrot.imitate.zombie_villager");
            ENTITY_PARROT_STEP = func_187510_a("entity.parrot.step");
            ENTITY_PIG_AMBIENT = func_187510_a("entity.pig.ambient");
            ENTITY_PIG_DEATH = func_187510_a("entity.pig.death");
            ENTITY_PIG_HURT = func_187510_a("entity.pig.hurt");
            ENTITY_PIG_SADDLE = func_187510_a("entity.pig.saddle");
            ENTITY_PIG_STEP = func_187510_a("entity.pig.step");
            BLOCK_PISTON_CONTRACT = func_187510_a("block.piston.contract");
            BLOCK_PISTON_EXTEND = func_187510_a("block.piston.extend");
            ENTITY_PLAYER_ATTACK_CRIT = func_187510_a("entity.player.attack.crit");
            ENTITY_PLAYER_ATTACK_KNOCKBACK = func_187510_a("entity.player.attack.knockback");
            ENTITY_PLAYER_ATTACK_NODAMAGE = func_187510_a("entity.player.attack.nodamage");
            ENTITY_PLAYER_ATTACK_STRONG = func_187510_a("entity.player.attack.strong");
            ENTITY_PLAYER_ATTACK_SWEEP = func_187510_a("entity.player.attack.sweep");
            ENTITY_PLAYER_ATTACK_WEAK = func_187510_a("entity.player.attack.weak");
            ENTITY_PLAYER_BIG_FALL = func_187510_a("entity.player.big_fall");
            ENTITY_PLAYER_BREATH = func_187510_a("entity.player.breath");
            ENTITY_PLAYER_BURP = func_187510_a("entity.player.burp");
            ENTITY_PLAYER_DEATH = func_187510_a("entity.player.death");
            ENTITY_PLAYER_HURT = func_187510_a("entity.player.hurt");
            ENTITY_PLAYER_HURT_DROWN = func_187510_a("entity.player.hurt_drown");
            ENTITY_PLAYER_HURT_ON_FIRE = func_187510_a("entity.player.hurt_on_fire");
            ENTITY_PLAYER_LEVELUP = func_187510_a("entity.player.levelup");
            ENTITY_PLAYER_SMALL_FALL = func_187510_a("entity.player.small_fall");
            ENTITY_PLAYER_SPLASH = func_187510_a("entity.player.splash");
            ENTITY_PLAYER_SWIM = func_187510_a("entity.player.swim");
            ENTITY_POLAR_BEAR_AMBIENT = func_187510_a("entity.polar_bear.ambient");
            ENTITY_POLAR_BEAR_AMBIENT_BABY = func_187510_a("entity.polar_bear.baby_ambient");
            ENTITY_POLAR_BEAR_DEATH = func_187510_a("entity.polar_bear.death");
            ENTITY_POLAR_BEAR_HURT = func_187510_a("entity.polar_bear.hurt");
            ENTITY_POLAR_BEAR_STEP = func_187510_a("entity.polar_bear.step");
            ENTITY_POLAR_BEAR_WARNING = func_187510_a("entity.polar_bear.warning");
            BLOCK_PORTAL_AMBIENT = func_187510_a("block.portal.ambient");
            BLOCK_PORTAL_TRAVEL = func_187510_a("block.portal.travel");
            BLOCK_PORTAL_TRIGGER = func_187510_a("block.portal.trigger");
            ENTITY_RABBIT_AMBIENT = func_187510_a("entity.rabbit.ambient");
            ENTITY_RABBIT_ATTACK = func_187510_a("entity.rabbit.attack");
            ENTITY_RABBIT_DEATH = func_187510_a("entity.rabbit.death");
            ENTITY_RABBIT_HURT = func_187510_a("entity.rabbit.hurt");
            ENTITY_RABBIT_JUMP = func_187510_a("entity.rabbit.jump");
            MUSIC_DISC_11 = func_187510_a("record.11");
            MUSIC_DISC_13 = func_187510_a("record.13");
            MUSIC_DISC_BLOCKS = func_187510_a("record.blocks");
            MUSIC_DISC_CAT = func_187510_a("record.cat");
            MUSIC_DISC_CHIRP = func_187510_a("record.chirp");
            MUSIC_DISC_FAR = func_187510_a("record.far");
            MUSIC_DISC_MALL = func_187510_a("record.mall");
            MUSIC_DISC_MELLOHI = func_187510_a("record.mellohi");
            MUSIC_DISC_STAL = func_187510_a("record.stal");
            MUSIC_DISC_STRAD = func_187510_a("record.strad");
            MUSIC_DISC_WAIT = func_187510_a("record.wait");
            MUSIC_DISC_WARD = func_187510_a("record.ward");
            BLOCK_REDSTONE_TORCH_BURNOUT = func_187510_a("block.redstone_torch.burnout");
            BLOCK_SAND_BREAK = func_187510_a("block.sand.break");
            BLOCK_SAND_FALL = func_187510_a("block.sand.fall");
            BLOCK_SAND_HIT = func_187510_a("block.sand.hit");
            BLOCK_SAND_PLACE = func_187510_a("block.sand.place");
            BLOCK_SAND_STEP = func_187510_a("block.sand.step");
            ENTITY_SHEEP_AMBIENT = func_187510_a("entity.sheep.ambient");
            ENTITY_SHEEP_DEATH = func_187510_a("entity.sheep.death");
            ENTITY_SHEEP_HURT = func_187510_a("entity.sheep.hurt");
            ENTITY_SHEEP_SHEAR = func_187510_a("entity.sheep.shear");
            ENTITY_SHEEP_STEP = func_187510_a("entity.sheep.step");
            ITEM_SHIELD_BLOCK = func_187510_a("item.shield.block");
            ITEM_SHIELD_BREAK = func_187510_a("item.shield.break");
            ITEM_SHOVEL_FLATTEN = func_187510_a("item.shovel.flatten");
            ENTITY_SHULKER_AMBIENT = func_187510_a("entity.shulker.ambient");
            BLOCK_SHULKER_BOX_CLOSE = func_187510_a("block.shulker_box.close");
            BLOCK_SHULKER_BOX_OPEN = func_187510_a("block.shulker_box.open");
            ENTITY_SHULKER_BULLET_HIT = func_187510_a("entity.shulker_bullet.hit");
            ENTITY_SHULKER_BULLET_HURT = func_187510_a("entity.shulker_bullet.hurt");
            ENTITY_SHULKER_CLOSE = func_187510_a("entity.shulker.close");
            ENTITY_SHULKER_DEATH = func_187510_a("entity.shulker.death");
            ENTITY_SHULKER_HURT = func_187510_a("entity.shulker.hurt");
            ENTITY_SHULKER_HURT_CLOSED = func_187510_a("entity.shulker.hurt_closed");
            ENTITY_SHULKER_OPEN = func_187510_a("entity.shulker.open");
            ENTITY_SHULKER_SHOOT = func_187510_a("entity.shulker.shoot");
            ENTITY_SHULKER_TELEPORT = func_187510_a("entity.shulker.teleport");
            ENTITY_SILVERFISH_AMBIENT = func_187510_a("entity.silverfish.ambient");
            ENTITY_SILVERFISH_DEATH = func_187510_a("entity.silverfish.death");
            ENTITY_SILVERFISH_HURT = func_187510_a("entity.silverfish.hurt");
            ENTITY_SILVERFISH_STEP = func_187510_a("entity.silverfish.step");
            ENTITY_SKELETON_AMBIENT = func_187510_a("entity.skeleton.ambient");
            ENTITY_SKELETON_DEATH = func_187510_a("entity.skeleton.death");
            ENTITY_SKELETON_HORSE_AMBIENT = func_187510_a("entity.skeleton_horse.ambient");
            ENTITY_SKELETON_HORSE_DEATH = func_187510_a("entity.skeleton_horse.death");
            ENTITY_SKELETON_HORSE_HURT = func_187510_a("entity.skeleton_horse.hurt");
            ENTITY_SKELETON_HURT = func_187510_a("entity.skeleton.hurt");
            ENTITY_SKELETON_SHOOT = func_187510_a("entity.skeleton.shoot");
            ENTITY_SKELETON_STEP = func_187510_a("entity.skeleton.step");
            ENTITY_SLIME_ATTACK = func_187510_a("entity.slime.attack");
            BLOCK_SLIME_BLOCK_BREAK = func_187510_a("block.slime.break");
            ENTITY_SLIME_DEATH = func_187510_a("entity.slime.death");
            BLOCK_SLIME_BLOCK_FALL = func_187510_a("block.slime.fall");
            BLOCK_SLIME_BLOCK_HIT = func_187510_a("block.slime.hit");
            ENTITY_SLIME_HURT = func_187510_a("entity.slime.hurt");
            ENTITY_SLIME_JUMP = func_187510_a("entity.slime.jump");
            BLOCK_SLIME_BLOCK_PLACE = func_187510_a("block.slime.place");
            ENTITY_SLIME_SQUISH = func_187510_a("entity.slime.squish");
            BLOCK_SLIME_BLOCK_STEP = func_187510_a("block.slime.step");
            ENTITY_MAGMA_CUBE_DEATH_SMALL = func_187510_a("entity.small_magmacube.death");
            ENTITY_MAGMA_CUBE_HURT_SMALL = func_187510_a("entity.small_magmacube.hurt");
            ENTITY_MAGMA_CUBE_SQUISH_SMALL = func_187510_a("entity.small_magmacube.squish");
            ENTITY_SLIME_DEATH_SMALL = func_187510_a("entity.small_slime.death");
            ENTITY_SLIME_HURT_SMALL = func_187510_a("entity.small_slime.hurt");
            ENTITY_SLIME_JUMP_SMALL = func_187510_a("entity.small_slime.jump");
            ENTITY_SLIME_SQUISH_SMALL = func_187510_a("entity.small_slime.squish");
            ENTITY_SNOWBALL_THROW = func_187510_a("entity.snowball.throw");
            ENTITY_SNOW_GOLEM_AMBIENT = func_187510_a("entity.snowman.ambient");
            ENTITY_SNOW_GOLEM_DEATH = func_187510_a("entity.snowman.death");
            ENTITY_SNOW_GOLEM_HURT = func_187510_a("entity.snowman.hurt");
            ENTITY_SNOW_GOLEM_SHOOT = func_187510_a("entity.snowman.shoot");
            BLOCK_SNOW_BREAK = func_187510_a("block.snow.break");
            BLOCK_SNOW_FALL = func_187510_a("block.snow.fall");
            BLOCK_SNOW_HIT = func_187510_a("block.snow.hit");
            BLOCK_SNOW_PLACE = func_187510_a("block.snow.place");
            BLOCK_SNOW_STEP = func_187510_a("block.snow.step");
            ENTITY_SPIDER_AMBIENT = func_187510_a("entity.spider.ambient");
            ENTITY_SPIDER_DEATH = func_187510_a("entity.spider.death");
            ENTITY_SPIDER_HURT = func_187510_a("entity.spider.hurt");
            ENTITY_SPIDER_STEP = func_187510_a("entity.spider.step");
            ENTITY_SPLASH_POTION_BREAK = func_187510_a("entity.splash_potion.break");
            ENTITY_SPLASH_POTION_THROW = func_187510_a("entity.splash_potion.throw");
            ENTITY_SQUID_AMBIENT = func_187510_a("entity.squid.ambient");
            ENTITY_SQUID_DEATH = func_187510_a("entity.squid.death");
            ENTITY_SQUID_HURT = func_187510_a("entity.squid.hurt");
            BLOCK_STONE_BREAK = func_187510_a("block.stone.break");
            BLOCK_STONE_BUTTON_CLICK_OFF = func_187510_a("block.stone_button.click_off");
            BLOCK_STONE_BUTTON_CLICK_ON = func_187510_a("block.stone_button.click_on");
            BLOCK_STONE_FALL = func_187510_a("block.stone.fall");
            BLOCK_STONE_HIT = func_187510_a("block.stone.hit");
            BLOCK_STONE_PLACE = func_187510_a("block.stone.place");
            BLOCK_STONE_PRESSURE_PLATE_CLICK_OFF = func_187510_a("block.stone_pressureplate.click_off");
            BLOCK_STONE_PRESSURE_PLATE_CLICK_ON = func_187510_a("block.stone_pressureplate.click_on");
            BLOCK_STONE_STEP = func_187510_a("block.stone.step");
            ENTITY_STRAY_AMBIENT = func_187510_a("entity.stray.ambient");
            ENTITY_STRAY_DEATH = func_187510_a("entity.stray.death");
            ENTITY_STRAY_HURT = func_187510_a("entity.stray.hurt");
            ENTITY_STRAY_STEP = func_187510_a("entity.stray.step");
            ENCHANT_THORNS_HIT = func_187510_a("enchant.thorns.hit");
            ENTITY_TNT_PRIMED = func_187510_a("entity.tnt.primed");
            ITEM_TOTEM_USE = func_187510_a("item.totem.use");
            BLOCK_TRIPWIRE_ATTACH = func_187510_a("block.tripwire.attach");
            BLOCK_TRIPWIRE_CLICK_OFF = func_187510_a("block.tripwire.click_off");
            BLOCK_TRIPWIRE_CLICK_ON = func_187510_a("block.tripwire.click_on");
            BLOCK_TRIPWIRE_DETACH = func_187510_a("block.tripwire.detach");
            UI_BUTTON_CLICK = func_187510_a("ui.button.click");
            UI_TOAST_IN = func_187510_a("ui.toast.in");
            UI_TOAST_OUT = func_187510_a("ui.toast.out");
            UI_TOAST_CHALLENGE_COMPLETE = func_187510_a("ui.toast.challenge_complete");
            ENTITY_VEX_AMBIENT = func_187510_a("entity.vex.ambient");
            ENTITY_VEX_CHARGE = func_187510_a("entity.vex.charge");
            ENTITY_VEX_DEATH = func_187510_a("entity.vex.death");
            ENTITY_VEX_HURT = func_187510_a("entity.vex.hurt");
            ENTITY_VILLAGER_AMBIENT = func_187510_a("entity.villager.ambient");
            ENTITY_VILLAGER_DEATH = func_187510_a("entity.villager.death");
            ENTITY_VILLAGER_HURT = func_187510_a("entity.villager.hurt");
            ENTITY_VILLAGER_NO = func_187510_a("entity.villager.no");
            ENTITY_VILLAGER_TRADE = func_187510_a("entity.villager.trading");
            ENTITY_VILLAGER_YES = func_187510_a("entity.villager.yes");
            ENTITY_VINDICATOR_AMBIENT = func_187510_a("entity.vindication_illager.ambient");
            ENTITY_VINDICATOR_DEATH = func_187510_a("entity.vindication_illager.death");
            ENTITY_VINDICATOR_HURT = func_187510_a("entity.vindication_illager.hurt");
            BLOCK_LILY_PAD_PLACE = func_187510_a("block.waterlily.place");
            BLOCK_WATER_AMBIENT = func_187510_a("block.water.ambient");
            WEATHER_RAIN = func_187510_a("weather.rain");
            WEATHER_RAIN_ABOVE = func_187510_a("weather.rain.above");
            ENTITY_WITCH_AMBIENT = func_187510_a("entity.witch.ambient");
            ENTITY_WITCH_DEATH = func_187510_a("entity.witch.death");
            ENTITY_WITCH_DRINK = func_187510_a("entity.witch.drink");
            ENTITY_WITCH_HURT = func_187510_a("entity.witch.hurt");
            ENTITY_WITCH_THROW = func_187510_a("entity.witch.throw");
            ENTITY_WITHER_AMBIENT = func_187510_a("entity.wither.ambient");
            ENTITY_WITHER_BREAK_BLOCK = func_187510_a("entity.wither.break_block");
            ENTITY_WITHER_DEATH = func_187510_a("entity.wither.death");
            ENTITY_WITHER_HURT = func_187510_a("entity.wither.hurt");
            ENTITY_WITHER_SHOOT = func_187510_a("entity.wither.shoot");
            ENTITY_WITHER_SKELETON_AMBIENT = func_187510_a("entity.wither_skeleton.ambient");
            ENTITY_WITHER_SKELETON_DEATH = func_187510_a("entity.wither_skeleton.death");
            ENTITY_WITHER_SKELETON_HURT = func_187510_a("entity.wither_skeleton.hurt");
            ENTITY_WITHER_SKELETON_STEP = func_187510_a("entity.wither_skeleton.step");
            ENTITY_WITHER_SPAWN = func_187510_a("entity.wither.spawn");
            ENTITY_WOLF_AMBIENT = func_187510_a("entity.wolf.ambient");
            ENTITY_WOLF_DEATH = func_187510_a("entity.wolf.death");
            ENTITY_WOLF_GROWL = func_187510_a("entity.wolf.growl");
            ENTITY_WOLF_HOWL = func_187510_a("entity.wolf.howl");
            ENTITY_WOLF_HURT = func_187510_a("entity.wolf.hurt");
            ENTITY_WOLF_PANT = func_187510_a("entity.wolf.pant");
            ENTITY_WOLF_SHAKE = func_187510_a("entity.wolf.shake");
            ENTITY_WOLF_STEP = func_187510_a("entity.wolf.step");
            ENTITY_WOLF_WHINE = func_187510_a("entity.wolf.whine");
            BLOCK_WOODEN_DOOR_CLOSE = func_187510_a("block.wooden_door.close");
            BLOCK_WOODEN_DOOR_OPEN = func_187510_a("block.wooden_door.open");
            BLOCK_WOODEN_TRAPDOOR_CLOSE = func_187510_a("block.wooden_trapdoor.close");
            BLOCK_WOODEN_TRAPDOOR_OPEN = func_187510_a("block.wooden_trapdoor.open");
            BLOCK_WOOD_BREAK = func_187510_a("block.wood.break");
            BLOCK_WOODEN_BUTTON_CLICK_OFF = func_187510_a("block.wood_button.click_off");
            BLOCK_WOODEN_BUTTON_CLICK_ON = func_187510_a("block.wood_button.click_on");
            BLOCK_WOOD_FALL = func_187510_a("block.wood.fall");
            BLOCK_WOOD_HIT = func_187510_a("block.wood.hit");
            BLOCK_WOOD_PLACE = func_187510_a("block.wood.place");
            BLOCK_WOODEN_PRESSURE_PLATE_CLICK_OFF = func_187510_a("block.wood_pressureplate.click_off");
            BLOCK_WOODEN_PRESSURE_PLATE_CLICK_ON = func_187510_a("block.wood_pressureplate.click_on");
            BLOCK_WOOD_STEP = func_187510_a("block.wood.step");
            ENTITY_ZOMBIE_AMBIENT = func_187510_a("entity.zombie.ambient");
            ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR = func_187510_a("entity.zombie.attack_door_wood");
            ENTITY_ZOMBIE_ATTACK_IRON_DOOR = func_187510_a("entity.zombie.attack_iron_door");
            ENTITY_ZOMBIE_BREAK_WOODEN_DOOR = func_187510_a("entity.zombie.break_door_wood");
            ENTITY_ZOMBIE_DEATH = func_187510_a("entity.zombie.death");
            ENTITY_ZOMBIE_HORSE_AMBIENT = func_187510_a("entity.zombie_horse.ambient");
            ENTITY_ZOMBIE_HORSE_DEATH = func_187510_a("entity.zombie_horse.death");
            ENTITY_ZOMBIE_HORSE_HURT = func_187510_a("entity.zombie_horse.hurt");
            ENTITY_ZOMBIE_HURT = func_187510_a("entity.zombie.hurt");
            ENTITY_ZOMBIE_INFECT = func_187510_a("entity.zombie.infect");
            ENTITY_ZOMBIE_PIGMAN_AMBIENT = func_187510_a("entity.zombie_pig.ambient");
            ENTITY_ZOMBIE_PIGMAN_ANGRY = func_187510_a("entity.zombie_pig.angry");
            ENTITY_ZOMBIE_PIGMAN_DEATH = func_187510_a("entity.zombie_pig.death");
            ENTITY_ZOMBIE_PIGMAN_HURT = func_187510_a("entity.zombie_pig.hurt");
            ENTITY_ZOMBIE_STEP = func_187510_a("entity.zombie.step");
            ENTITY_ZOMBIE_VILLAGER_AMBIENT = func_187510_a("entity.zombie_villager.ambient");
            ENTITY_ZOMBIE_VILLAGER_CONVERTED = func_187510_a("entity.zombie_villager.converted");
            ENTITY_ZOMBIE_VILLAGER_CURE = func_187510_a("entity.zombie_villager.cure");
            ENTITY_ZOMBIE_VILLAGER_DEATH = func_187510_a("entity.zombie_villager.death");
            ENTITY_ZOMBIE_VILLAGER_HURT = func_187510_a("entity.zombie_villager.hurt");
            ENTITY_ZOMBIE_VILLAGER_STEP = func_187510_a("entity.zombie_villager.step");
        }
    }
}
